// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"
	"reagent/common"
	"reagent/config"
	"reagent/container"
	"time"

	"github.com/docker/docker/api/types"
	container0 "github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/events"
	"github.com/docker/docker/api/types/network"
	mock "github.com/stretchr/testify/mock"
)

// NewContainer creates a new instance of Container. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Container {
	mock := &Container{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Container is an autogenerated mock type for the Container type
type Container struct {
	mock.Mock
}

type Container_Expecter struct {
	mock *mock.Mock
}

func (_m *Container) EXPECT() *Container_Expecter {
	return &Container_Expecter{mock: &_m.Mock}
}

// Attach provides a mock function for the type Container
func (_mock *Container) Attach(ctx context.Context, containerName string, shell string) (container.HijackedResponse, error) {
	ret := _mock.Called(ctx, containerName, shell)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 container.HijackedResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (container.HijackedResponse, error)); ok {
		return returnFunc(ctx, containerName, shell)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) container.HijackedResponse); ok {
		r0 = returnFunc(ctx, containerName, shell)
	} else {
		r0 = ret.Get(0).(container.HijackedResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, containerName, shell)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_Attach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attach'
type Container_Attach_Call struct {
	*mock.Call
}

// Attach is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - shell string
func (_e *Container_Expecter) Attach(ctx any, containerName any, shell any) *Container_Attach_Call {
	return &Container_Attach_Call{Call: _e.mock.On("Attach", ctx, containerName, shell)}
}

func (_c *Container_Attach_Call) Run(run func(ctx context.Context, containerName string, shell string)) *Container_Attach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_Attach_Call) Return(hijackedResponse container.HijackedResponse, err error) *Container_Attach_Call {
	_c.Call.Return(hijackedResponse, err)
	return _c
}

func (_c *Container_Attach_Call) RunAndReturn(run func(ctx context.Context, containerName string, shell string) (container.HijackedResponse, error)) *Container_Attach_Call {
	_c.Call.Return(run)
	return _c
}

// Build provides a mock function for the type Container
func (_mock *Container) Build(ctx context.Context, pathToTar string, options types.ImageBuildOptions) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, pathToTar, options)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.ImageBuildOptions) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, pathToTar, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.ImageBuildOptions) io.ReadCloser); ok {
		r0 = returnFunc(ctx, pathToTar, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.ImageBuildOptions) error); ok {
		r1 = returnFunc(ctx, pathToTar, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type Container_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - pathToTar string
//   - options types.ImageBuildOptions
func (_e *Container_Expecter) Build(ctx any, pathToTar any, options any) *Container_Build_Call {
	return &Container_Build_Call{Call: _e.mock.On("Build", ctx, pathToTar, options)}
}

func (_c *Container_Build_Call) Run(run func(ctx context.Context, pathToTar string, options types.ImageBuildOptions)) *Container_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.ImageBuildOptions
		if args[2] != nil {
			arg2 = args[2].(types.ImageBuildOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_Build_Call) Return(readCloser io.ReadCloser, err error) *Container_Build_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *Container_Build_Call) RunAndReturn(run func(ctx context.Context, pathToTar string, options types.ImageBuildOptions) (io.ReadCloser, error)) *Container_Build_Call {
	_c.Call.Return(run)
	return _c
}

// CancelAllStreams provides a mock function for the type Container
func (_mock *Container) CancelAllStreams() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CancelAllStreams")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_CancelAllStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelAllStreams'
type Container_CancelAllStreams_Call struct {
	*mock.Call
}

// CancelAllStreams is a helper method to define mock.On call
func (_e *Container_Expecter) CancelAllStreams() *Container_CancelAllStreams_Call {
	return &Container_CancelAllStreams_Call{Call: _e.mock.On("CancelAllStreams")}
}

func (_c *Container_CancelAllStreams_Call) Run(run func()) *Container_CancelAllStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Container_CancelAllStreams_Call) Return(err error) *Container_CancelAllStreams_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_CancelAllStreams_Call) RunAndReturn(run func() error) *Container_CancelAllStreams_Call {
	_c.Call.Return(run)
	return _c
}

// CancelStream provides a mock function for the type Container
func (_mock *Container) CancelStream(cancelID string) error {
	ret := _mock.Called(cancelID)

	if len(ret) == 0 {
		panic("no return value specified for CancelStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(cancelID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_CancelStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelStream'
type Container_CancelStream_Call struct {
	*mock.Call
}

// CancelStream is a helper method to define mock.On call
//   - cancelID string
func (_e *Container_Expecter) CancelStream(cancelID any) *Container_CancelStream_Call {
	return &Container_CancelStream_Call{Call: _e.mock.On("CancelStream", cancelID)}
}

func (_c *Container_CancelStream_Call) Run(run func(cancelID string)) *Container_CancelStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_CancelStream_Call) Return(err error) *Container_CancelStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_CancelStream_Call) RunAndReturn(run func(cancelID string) error) *Container_CancelStream_Call {
	_c.Call.Return(run)
	return _c
}

// Compose provides a mock function for the type Container
func (_mock *Container) Compose() *container.Compose {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Compose")
	}

	var r0 *container.Compose
	if returnFunc, ok := ret.Get(0).(func() *container.Compose); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*container.Compose)
		}
	}
	return r0
}

// Container_Compose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compose'
type Container_Compose_Call struct {
	*mock.Call
}

// Compose is a helper method to define mock.On call
func (_e *Container_Expecter) Compose() *Container_Compose_Call {
	return &Container_Compose_Call{Call: _e.mock.On("Compose")}
}

func (_c *Container_Compose_Call) Run(run func()) *Container_Compose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Container_Compose_Call) Return(compose *container.Compose) *Container_Compose_Call {
	_c.Call.Return(compose)
	return _c
}

func (_c *Container_Compose_Call) RunAndReturn(run func() *container.Compose) *Container_Compose_Call {
	_c.Call.Return(run)
	return _c
}

// CreateContainer provides a mock function for the type Container
func (_mock *Container) CreateContainer(ctx context.Context, cConfig container0.Config, hConfig container0.HostConfig, nConfig network.NetworkingConfig, containerName string) (string, error) {
	ret := _mock.Called(ctx, cConfig, hConfig, nConfig, containerName)

	if len(ret) == 0 {
		panic("no return value specified for CreateContainer")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, container0.Config, container0.HostConfig, network.NetworkingConfig, string) (string, error)); ok {
		return returnFunc(ctx, cConfig, hConfig, nConfig, containerName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, container0.Config, container0.HostConfig, network.NetworkingConfig, string) string); ok {
		r0 = returnFunc(ctx, cConfig, hConfig, nConfig, containerName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, container0.Config, container0.HostConfig, network.NetworkingConfig, string) error); ok {
		r1 = returnFunc(ctx, cConfig, hConfig, nConfig, containerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_CreateContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateContainer'
type Container_CreateContainer_Call struct {
	*mock.Call
}

// CreateContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - cConfig container0.Config
//   - hConfig container0.HostConfig
//   - nConfig network.NetworkingConfig
//   - containerName string
func (_e *Container_Expecter) CreateContainer(ctx any, cConfig any, hConfig any, nConfig any, containerName any) *Container_CreateContainer_Call {
	return &Container_CreateContainer_Call{Call: _e.mock.On("CreateContainer", ctx, cConfig, hConfig, nConfig, containerName)}
}

func (_c *Container_CreateContainer_Call) Run(run func(ctx context.Context, cConfig container0.Config, hConfig container0.HostConfig, nConfig network.NetworkingConfig, containerName string)) *Container_CreateContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 container0.Config
		if args[1] != nil {
			arg1 = args[1].(container0.Config)
		}
		var arg2 container0.HostConfig
		if args[2] != nil {
			arg2 = args[2].(container0.HostConfig)
		}
		var arg3 network.NetworkingConfig
		if args[3] != nil {
			arg3 = args[3].(network.NetworkingConfig)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Container_CreateContainer_Call) Return(s string, err error) *Container_CreateContainer_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Container_CreateContainer_Call) RunAndReturn(run func(ctx context.Context, cConfig container0.Config, hConfig container0.HostConfig, nConfig network.NetworkingConfig, containerName string) (string, error)) *Container_CreateContainer_Call {
	_c.Call.Return(run)
	return _c
}

// ExecAttach provides a mock function for the type Container
func (_mock *Container) ExecAttach(ctx context.Context, containerName string, shell string) (container.HijackedResponse, error) {
	ret := _mock.Called(ctx, containerName, shell)

	if len(ret) == 0 {
		panic("no return value specified for ExecAttach")
	}

	var r0 container.HijackedResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (container.HijackedResponse, error)); ok {
		return returnFunc(ctx, containerName, shell)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) container.HijackedResponse); ok {
		r0 = returnFunc(ctx, containerName, shell)
	} else {
		r0 = ret.Get(0).(container.HijackedResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, containerName, shell)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_ExecAttach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecAttach'
type Container_ExecAttach_Call struct {
	*mock.Call
}

// ExecAttach is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - shell string
func (_e *Container_Expecter) ExecAttach(ctx any, containerName any, shell any) *Container_ExecAttach_Call {
	return &Container_ExecAttach_Call{Call: _e.mock.On("ExecAttach", ctx, containerName, shell)}
}

func (_c *Container_ExecAttach_Call) Run(run func(ctx context.Context, containerName string, shell string)) *Container_ExecAttach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_ExecAttach_Call) Return(hijackedResponse container.HijackedResponse, err error) *Container_ExecAttach_Call {
	_c.Call.Return(hijackedResponse, err)
	return _c
}

func (_c *Container_ExecAttach_Call) RunAndReturn(run func(ctx context.Context, containerName string, shell string) (container.HijackedResponse, error)) *Container_ExecAttach_Call {
	_c.Call.Return(run)
	return _c
}

// ExecCommand provides a mock function for the type Container
func (_mock *Container) ExecCommand(ctx context.Context, containerName string, cmd []string) (container.HijackedResponse, error) {
	ret := _mock.Called(ctx, containerName, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ExecCommand")
	}

	var r0 container.HijackedResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (container.HijackedResponse, error)); ok {
		return returnFunc(ctx, containerName, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) container.HijackedResponse); ok {
		r0 = returnFunc(ctx, containerName, cmd)
	} else {
		r0 = ret.Get(0).(container.HijackedResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, containerName, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_ExecCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecCommand'
type Container_ExecCommand_Call struct {
	*mock.Call
}

// ExecCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - cmd []string
func (_e *Container_Expecter) ExecCommand(ctx any, containerName any, cmd any) *Container_ExecCommand_Call {
	return &Container_ExecCommand_Call{Call: _e.mock.On("ExecCommand", ctx, containerName, cmd)}
}

func (_c *Container_ExecCommand_Call) Run(run func(ctx context.Context, containerName string, cmd []string)) *Container_ExecCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_ExecCommand_Call) Return(hijackedResponse container.HijackedResponse, err error) *Container_ExecCommand_Call {
	_c.Call.Return(hijackedResponse, err)
	return _c
}

func (_c *Container_ExecCommand_Call) RunAndReturn(run func(ctx context.Context, containerName string, cmd []string) (container.HijackedResponse, error)) *Container_ExecCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type Container
func (_mock *Container) GetConfig() *config.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *config.Config
	if returnFunc, ok := ret.Get(0).(func() *config.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Config)
		}
	}
	return r0
}

// Container_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type Container_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *Container_Expecter) GetConfig() *Container_GetConfig_Call {
	return &Container_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *Container_GetConfig_Call) Run(run func()) *Container_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Container_GetConfig_Call) Return(config1 *config.Config) *Container_GetConfig_Call {
	_c.Call.Return(config1)
	return _c
}

func (_c *Container_GetConfig_Call) RunAndReturn(run func() *config.Config) *Container_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainer provides a mock function for the type Container
func (_mock *Container) GetContainer(ctx context.Context, containerName string) (types.Container, error) {
	ret := _mock.Called(ctx, containerName)

	if len(ret) == 0 {
		panic("no return value specified for GetContainer")
	}

	var r0 types.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (types.Container, error)); ok {
		return returnFunc(ctx, containerName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) types.Container); ok {
		r0 = returnFunc(ctx, containerName)
	} else {
		r0 = ret.Get(0).(types.Container)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, containerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_GetContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainer'
type Container_GetContainer_Call struct {
	*mock.Call
}

// GetContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
func (_e *Container_Expecter) GetContainer(ctx any, containerName any) *Container_GetContainer_Call {
	return &Container_GetContainer_Call{Call: _e.mock.On("GetContainer", ctx, containerName)}
}

func (_c *Container_GetContainer_Call) Run(run func(ctx context.Context, containerName string)) *Container_GetContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Container_GetContainer_Call) Return(v types.Container, err error) *Container_GetContainer_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Container_GetContainer_Call) RunAndReturn(run func(ctx context.Context, containerName string) (types.Container, error)) *Container_GetContainer_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainerNetworkMode provides a mock function for the type Container
func (_mock *Container) GetContainerNetworkMode(ctx context.Context, containerName string) (string, error) {
	ret := _mock.Called(ctx, containerName)

	if len(ret) == 0 {
		panic("no return value specified for GetContainerNetworkMode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, containerName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, containerName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, containerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_GetContainerNetworkMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainerNetworkMode'
type Container_GetContainerNetworkMode_Call struct {
	*mock.Call
}

// GetContainerNetworkMode is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
func (_e *Container_Expecter) GetContainerNetworkMode(ctx any, containerName any) *Container_GetContainerNetworkMode_Call {
	return &Container_GetContainerNetworkMode_Call{Call: _e.mock.On("GetContainerNetworkMode", ctx, containerName)}
}

func (_c *Container_GetContainerNetworkMode_Call) Run(run func(ctx context.Context, containerName string)) *Container_GetContainerNetworkMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Container_GetContainerNetworkMode_Call) Return(s string, err error) *Container_GetContainerNetworkMode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Container_GetContainerNetworkMode_Call) RunAndReturn(run func(ctx context.Context, containerName string) (string, error)) *Container_GetContainerNetworkMode_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainerPortBindings provides a mock function for the type Container
func (_mock *Container) GetContainerPortBindings(ctx context.Context, containerName string) (map[string]uint64, error) {
	ret := _mock.Called(ctx, containerName)

	if len(ret) == 0 {
		panic("no return value specified for GetContainerPortBindings")
	}

	var r0 map[string]uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]uint64, error)); ok {
		return returnFunc(ctx, containerName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]uint64); ok {
		r0 = returnFunc(ctx, containerName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, containerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_GetContainerPortBindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainerPortBindings'
type Container_GetContainerPortBindings_Call struct {
	*mock.Call
}

// GetContainerPortBindings is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
func (_e *Container_Expecter) GetContainerPortBindings(ctx any, containerName any) *Container_GetContainerPortBindings_Call {
	return &Container_GetContainerPortBindings_Call{Call: _e.mock.On("GetContainerPortBindings", ctx, containerName)}
}

func (_c *Container_GetContainerPortBindings_Call) Run(run func(ctx context.Context, containerName string)) *Container_GetContainerPortBindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Container_GetContainerPortBindings_Call) Return(stringToUint64 map[string]uint64, err error) *Container_GetContainerPortBindings_Call {
	_c.Call.Return(stringToUint64, err)
	return _c
}

func (_c *Container_GetContainerPortBindings_Call) RunAndReturn(run func(ctx context.Context, containerName string) (map[string]uint64, error)) *Container_GetContainerPortBindings_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainerState provides a mock function for the type Container
func (_mock *Container) GetContainerState(ctx context.Context, containerName string) (container.ContainerState, error) {
	ret := _mock.Called(ctx, containerName)

	if len(ret) == 0 {
		panic("no return value specified for GetContainerState")
	}

	var r0 container.ContainerState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (container.ContainerState, error)); ok {
		return returnFunc(ctx, containerName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) container.ContainerState); ok {
		r0 = returnFunc(ctx, containerName)
	} else {
		r0 = ret.Get(0).(container.ContainerState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, containerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_GetContainerState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainerState'
type Container_GetContainerState_Call struct {
	*mock.Call
}

// GetContainerState is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
func (_e *Container_Expecter) GetContainerState(ctx any, containerName any) *Container_GetContainerState_Call {
	return &Container_GetContainerState_Call{Call: _e.mock.On("GetContainerState", ctx, containerName)}
}

func (_c *Container_GetContainerState_Call) Run(run func(ctx context.Context, containerName string)) *Container_GetContainerState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Container_GetContainerState_Call) Return(containerState container.ContainerState, err error) *Container_GetContainerState_Call {
	_c.Call.Return(containerState, err)
	return _c
}

func (_c *Container_GetContainerState_Call) RunAndReturn(run func(ctx context.Context, containerName string) (container.ContainerState, error)) *Container_GetContainerState_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainers provides a mock function for the type Container
func (_mock *Container) GetContainers(ctx context.Context) ([]types.Container, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetContainers")
	}

	var r0 []types.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]types.Container, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []types.Container); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_GetContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainers'
type Container_GetContainers_Call struct {
	*mock.Call
}

// GetContainers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Container_Expecter) GetContainers(ctx any) *Container_GetContainers_Call {
	return &Container_GetContainers_Call{Call: _e.mock.On("GetContainers", ctx)}
}

func (_c *Container_GetContainers_Call) Run(run func(ctx context.Context)) *Container_GetContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_GetContainers_Call) Return(vs []types.Container, err error) *Container_GetContainers_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Container_GetContainers_Call) RunAndReturn(run func(ctx context.Context) ([]types.Container, error)) *Container_GetContainers_Call {
	_c.Call.Return(run)
	return _c
}

// GetImage provides a mock function for the type Container
func (_mock *Container) GetImage(ctx context.Context, fullImageName string, tag string) (container.ImageResult, error) {
	ret := _mock.Called(ctx, fullImageName, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetImage")
	}

	var r0 container.ImageResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (container.ImageResult, error)); ok {
		return returnFunc(ctx, fullImageName, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) container.ImageResult); ok {
		r0 = returnFunc(ctx, fullImageName, tag)
	} else {
		r0 = ret.Get(0).(container.ImageResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, fullImageName, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_GetImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImage'
type Container_GetImage_Call struct {
	*mock.Call
}

// GetImage is a helper method to define mock.On call
//   - ctx context.Context
//   - fullImageName string
//   - tag string
func (_e *Container_Expecter) GetImage(ctx any, fullImageName any, tag any) *Container_GetImage_Call {
	return &Container_GetImage_Call{Call: _e.mock.On("GetImage", ctx, fullImageName, tag)}
}

func (_c *Container_GetImage_Call) Run(run func(ctx context.Context, fullImageName string, tag string)) *Container_GetImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_GetImage_Call) Return(imageResult container.ImageResult, err error) *Container_GetImage_Call {
	_c.Call.Return(imageResult, err)
	return _c
}

func (_c *Container_GetImage_Call) RunAndReturn(run func(ctx context.Context, fullImageName string, tag string) (container.ImageResult, error)) *Container_GetImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetImages provides a mock function for the type Container
func (_mock *Container) GetImages(ctx context.Context, fullImageName string) ([]container.ImageResult, error) {
	ret := _mock.Called(ctx, fullImageName)

	if len(ret) == 0 {
		panic("no return value specified for GetImages")
	}

	var r0 []container.ImageResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]container.ImageResult, error)); ok {
		return returnFunc(ctx, fullImageName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []container.ImageResult); ok {
		r0 = returnFunc(ctx, fullImageName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]container.ImageResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fullImageName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_GetImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImages'
type Container_GetImages_Call struct {
	*mock.Call
}

// GetImages is a helper method to define mock.On call
//   - ctx context.Context
//   - fullImageName string
func (_e *Container_Expecter) GetImages(ctx any, fullImageName any) *Container_GetImages_Call {
	return &Container_GetImages_Call{Call: _e.mock.On("GetImages", ctx, fullImageName)}
}

func (_c *Container_GetImages_Call) Run(run func(ctx context.Context, fullImageName string)) *Container_GetImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Container_GetImages_Call) Return(imageResults []container.ImageResult, err error) *Container_GetImages_Call {
	_c.Call.Return(imageResults, err)
	return _c
}

func (_c *Container_GetImages_Call) RunAndReturn(run func(ctx context.Context, fullImageName string) ([]container.ImageResult, error)) *Container_GetImages_Call {
	_c.Call.Return(run)
	return _c
}

// HandleRegistryLogins provides a mock function for the type Container
func (_mock *Container) HandleRegistryLogins(credentials map[string]common.DockerCredential) error {
	ret := _mock.Called(credentials)

	if len(ret) == 0 {
		panic("no return value specified for HandleRegistryLogins")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[string]common.DockerCredential) error); ok {
		r0 = returnFunc(credentials)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_HandleRegistryLogins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRegistryLogins'
type Container_HandleRegistryLogins_Call struct {
	*mock.Call
}

// HandleRegistryLogins is a helper method to define mock.On call
//   - credentials map[string]common.DockerCredential
func (_e *Container_Expecter) HandleRegistryLogins(credentials any) *Container_HandleRegistryLogins_Call {
	return &Container_HandleRegistryLogins_Call{Call: _e.mock.On("HandleRegistryLogins", credentials)}
}

func (_c *Container_HandleRegistryLogins_Call) Run(run func(credentials map[string]common.DockerCredential)) *Container_HandleRegistryLogins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]common.DockerCredential
		if args[0] != nil {
			arg0 = args[0].(map[string]common.DockerCredential)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_HandleRegistryLogins_Call) Return(err error) *Container_HandleRegistryLogins_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_HandleRegistryLogins_Call) RunAndReturn(run func(credentials map[string]common.DockerCredential) error) *Container_HandleRegistryLogins_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainers provides a mock function for the type Container
func (_mock *Container) ListContainers(ctx context.Context, options common.Dict) ([]container.ContainerResult, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 []container.ContainerResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Dict) ([]container.ContainerResult, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Dict) []container.ContainerResult); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]container.ContainerResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Dict) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type Container_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - ctx context.Context
//   - options common.Dict
func (_e *Container_Expecter) ListContainers(ctx any, options any) *Container_ListContainers_Call {
	return &Container_ListContainers_Call{Call: _e.mock.On("ListContainers", ctx, options)}
}

func (_c *Container_ListContainers_Call) Run(run func(ctx context.Context, options common.Dict)) *Container_ListContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Dict
		if args[1] != nil {
			arg1 = args[1].(common.Dict)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Container_ListContainers_Call) Return(containerResults []container.ContainerResult, err error) *Container_ListContainers_Call {
	_c.Call.Return(containerResults, err)
	return _c
}

func (_c *Container_ListContainers_Call) RunAndReturn(run func(ctx context.Context, options common.Dict) ([]container.ContainerResult, error)) *Container_ListContainers_Call {
	_c.Call.Return(run)
	return _c
}

// ListDanglingVolumes provides a mock function for the type Container
func (_mock *Container) ListDanglingVolumes(ctx context.Context) ([]container.VolumeResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDanglingVolumes")
	}

	var r0 []container.VolumeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]container.VolumeResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []container.VolumeResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]container.VolumeResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_ListDanglingVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDanglingVolumes'
type Container_ListDanglingVolumes_Call struct {
	*mock.Call
}

// ListDanglingVolumes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Container_Expecter) ListDanglingVolumes(ctx any) *Container_ListDanglingVolumes_Call {
	return &Container_ListDanglingVolumes_Call{Call: _e.mock.On("ListDanglingVolumes", ctx)}
}

func (_c *Container_ListDanglingVolumes_Call) Run(run func(ctx context.Context)) *Container_ListDanglingVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_ListDanglingVolumes_Call) Return(volumeResults []container.VolumeResult, err error) *Container_ListDanglingVolumes_Call {
	_c.Call.Return(volumeResults, err)
	return _c
}

func (_c *Container_ListDanglingVolumes_Call) RunAndReturn(run func(ctx context.Context) ([]container.VolumeResult, error)) *Container_ListDanglingVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// ListImages provides a mock function for the type Container
func (_mock *Container) ListImages(ctx context.Context, options map[string]interface{}) ([]container.ImageResult, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 []container.ImageResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}) ([]container.ImageResult, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]interface{}) []container.ImageResult); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]container.ImageResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_ListImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImages'
type Container_ListImages_Call struct {
	*mock.Call
}

// ListImages is a helper method to define mock.On call
//   - ctx context.Context
//   - options map[string]interface{}
func (_e *Container_Expecter) ListImages(ctx any, options any) *Container_ListImages_Call {
	return &Container_ListImages_Call{Call: _e.mock.On("ListImages", ctx, options)}
}

func (_c *Container_ListImages_Call) Run(run func(ctx context.Context, options map[string]interface{})) *Container_ListImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Container_ListImages_Call) Return(imageResults []container.ImageResult, err error) *Container_ListImages_Call {
	_c.Call.Return(imageResults, err)
	return _c
}

func (_c *Container_ListImages_Call) RunAndReturn(run func(ctx context.Context, options map[string]interface{}) ([]container.ImageResult, error)) *Container_ListImages_Call {
	_c.Call.Return(run)
	return _c
}

// ListenForContainerEvents provides a mock function for the type Container
func (_mock *Container) ListenForContainerEvents(ctx context.Context) (<-chan events.Message, <-chan error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListenForContainerEvents")
	}

	var r0 <-chan events.Message
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan events.Message, <-chan error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan events.Message); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan events.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) <-chan error); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// Container_ListenForContainerEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenForContainerEvents'
type Container_ListenForContainerEvents_Call struct {
	*mock.Call
}

// ListenForContainerEvents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Container_Expecter) ListenForContainerEvents(ctx any) *Container_ListenForContainerEvents_Call {
	return &Container_ListenForContainerEvents_Call{Call: _e.mock.On("ListenForContainerEvents", ctx)}
}

func (_c *Container_ListenForContainerEvents_Call) Run(run func(ctx context.Context)) *Container_ListenForContainerEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_ListenForContainerEvents_Call) Return(messageCh <-chan events.Message, errCh <-chan error) *Container_ListenForContainerEvents_Call {
	_c.Call.Return(messageCh, errCh)
	return _c
}

func (_c *Container_ListenForContainerEvents_Call) RunAndReturn(run func(ctx context.Context) (<-chan events.Message, <-chan error)) *Container_ListenForContainerEvents_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type Container
func (_mock *Container) Login(ctx context.Context, serverAddress string, username string, password string) (string, error) {
	ret := _mock.Called(ctx, serverAddress, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, serverAddress, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, serverAddress, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, serverAddress, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Container_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - serverAddress string
//   - username string
//   - password string
func (_e *Container_Expecter) Login(ctx any, serverAddress any, username any, password any) *Container_Login_Call {
	return &Container_Login_Call{Call: _e.mock.On("Login", ctx, serverAddress, username, password)}
}

func (_c *Container_Login_Call) Run(run func(ctx context.Context, serverAddress string, username string, password string)) *Container_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Container_Login_Call) Return(s string, err error) *Container_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Container_Login_Call) RunAndReturn(run func(ctx context.Context, serverAddress string, username string, password string) (string, error)) *Container_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function for the type Container
func (_mock *Container) Logs(ctx context.Context, containerName string, options common.Dict) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, containerName, options)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, common.Dict) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, containerName, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, common.Dict) io.ReadCloser); ok {
		r0 = returnFunc(ctx, containerName, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, common.Dict) error); ok {
		r1 = returnFunc(ctx, containerName, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type Container_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - options common.Dict
func (_e *Container_Expecter) Logs(ctx any, containerName any, options any) *Container_Logs_Call {
	return &Container_Logs_Call{Call: _e.mock.On("Logs", ctx, containerName, options)}
}

func (_c *Container_Logs_Call) Run(run func(ctx context.Context, containerName string, options common.Dict)) *Container_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 common.Dict
		if args[2] != nil {
			arg2 = args[2].(common.Dict)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_Logs_Call) Return(readCloser io.ReadCloser, err error) *Container_Logs_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *Container_Logs_Call) RunAndReturn(run func(ctx context.Context, containerName string, options common.Dict) (io.ReadCloser, error)) *Container_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type Container
func (_mock *Container) Ping(ctx context.Context) (container.Ping, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 container.Ping
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (container.Ping, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) container.Ping); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(container.Ping)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Container_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Container_Expecter) Ping(ctx any) *Container_Ping_Call {
	return &Container_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *Container_Ping_Call) Run(run func(ctx context.Context)) *Container_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_Ping_Call) Return(ping container.Ping, err error) *Container_Ping_Call {
	_c.Call.Return(ping, err)
	return _c
}

func (_c *Container_Ping_Call) RunAndReturn(run func(ctx context.Context) (container.Ping, error)) *Container_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// PollContainerState provides a mock function for the type Container
func (_mock *Container) PollContainerState(ctx context.Context, containerID string, pollingRate time.Duration) (<-chan container.ContainerState, <-chan error) {
	ret := _mock.Called(ctx, containerID, pollingRate)

	if len(ret) == 0 {
		panic("no return value specified for PollContainerState")
	}

	var r0 <-chan container.ContainerState
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (<-chan container.ContainerState, <-chan error)); ok {
		return returnFunc(ctx, containerID, pollingRate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) <-chan container.ContainerState); ok {
		r0 = returnFunc(ctx, containerID, pollingRate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan container.ContainerState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) <-chan error); ok {
		r1 = returnFunc(ctx, containerID, pollingRate)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// Container_PollContainerState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollContainerState'
type Container_PollContainerState_Call struct {
	*mock.Call
}

// PollContainerState is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - pollingRate time.Duration
func (_e *Container_Expecter) PollContainerState(ctx any, containerID any, pollingRate any) *Container_PollContainerState_Call {
	return &Container_PollContainerState_Call{Call: _e.mock.On("PollContainerState", ctx, containerID, pollingRate)}
}

func (_c *Container_PollContainerState_Call) Run(run func(ctx context.Context, containerID string, pollingRate time.Duration)) *Container_PollContainerState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_PollContainerState_Call) Return(containerStateCh <-chan container.ContainerState, errCh <-chan error) *Container_PollContainerState_Call {
	_c.Call.Return(containerStateCh, errCh)
	return _c
}

func (_c *Container_PollContainerState_Call) RunAndReturn(run func(ctx context.Context, containerID string, pollingRate time.Duration) (<-chan container.ContainerState, <-chan error)) *Container_PollContainerState_Call {
	_c.Call.Return(run)
	return _c
}

// PruneAllImages provides a mock function for the type Container
func (_mock *Container) PruneAllImages() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PruneAllImages")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_PruneAllImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneAllImages'
type Container_PruneAllImages_Call struct {
	*mock.Call
}

// PruneAllImages is a helper method to define mock.On call
func (_e *Container_Expecter) PruneAllImages() *Container_PruneAllImages_Call {
	return &Container_PruneAllImages_Call{Call: _e.mock.On("PruneAllImages")}
}

func (_c *Container_PruneAllImages_Call) Run(run func()) *Container_PruneAllImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Container_PruneAllImages_Call) Return(s string, err error) *Container_PruneAllImages_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Container_PruneAllImages_Call) RunAndReturn(run func() (string, error)) *Container_PruneAllImages_Call {
	_c.Call.Return(run)
	return _c
}

// PruneBuildCache provides a mock function for the type Container
func (_mock *Container) PruneBuildCache(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PruneBuildCache")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_PruneBuildCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneBuildCache'
type Container_PruneBuildCache_Call struct {
	*mock.Call
}

// PruneBuildCache is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Container_Expecter) PruneBuildCache(ctx any) *Container_PruneBuildCache_Call {
	return &Container_PruneBuildCache_Call{Call: _e.mock.On("PruneBuildCache", ctx)}
}

func (_c *Container_PruneBuildCache_Call) Run(run func(ctx context.Context)) *Container_PruneBuildCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_PruneBuildCache_Call) Return(s string, err error) *Container_PruneBuildCache_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Container_PruneBuildCache_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *Container_PruneBuildCache_Call {
	_c.Call.Return(run)
	return _c
}

// PruneDanglingImages provides a mock function for the type Container
func (_mock *Container) PruneDanglingImages(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PruneDanglingImages")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_PruneDanglingImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneDanglingImages'
type Container_PruneDanglingImages_Call struct {
	*mock.Call
}

// PruneDanglingImages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Container_Expecter) PruneDanglingImages(ctx any) *Container_PruneDanglingImages_Call {
	return &Container_PruneDanglingImages_Call{Call: _e.mock.On("PruneDanglingImages", ctx)}
}

func (_c *Container_PruneDanglingImages_Call) Run(run func(ctx context.Context)) *Container_PruneDanglingImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_PruneDanglingImages_Call) Return(s string, err error) *Container_PruneDanglingImages_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Container_PruneDanglingImages_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *Container_PruneDanglingImages_Call {
	_c.Call.Return(run)
	return _c
}

// PruneImages provides a mock function for the type Container
func (_mock *Container) PruneImages(ctx context.Context, options common.Dict) error {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for PruneImages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Dict) error); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_PruneImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneImages'
type Container_PruneImages_Call struct {
	*mock.Call
}

// PruneImages is a helper method to define mock.On call
//   - ctx context.Context
//   - options common.Dict
func (_e *Container_Expecter) PruneImages(ctx any, options any) *Container_PruneImages_Call {
	return &Container_PruneImages_Call{Call: _e.mock.On("PruneImages", ctx, options)}
}

func (_c *Container_PruneImages_Call) Run(run func(ctx context.Context, options common.Dict)) *Container_PruneImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Dict
		if args[1] != nil {
			arg1 = args[1].(common.Dict)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Container_PruneImages_Call) Return(err error) *Container_PruneImages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_PruneImages_Call) RunAndReturn(run func(ctx context.Context, options common.Dict) error) *Container_PruneImages_Call {
	_c.Call.Return(run)
	return _c
}

// PruneSystem provides a mock function for the type Container
func (_mock *Container) PruneSystem() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PruneSystem")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_PruneSystem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneSystem'
type Container_PruneSystem_Call struct {
	*mock.Call
}

// PruneSystem is a helper method to define mock.On call
func (_e *Container_Expecter) PruneSystem() *Container_PruneSystem_Call {
	return &Container_PruneSystem_Call{Call: _e.mock.On("PruneSystem")}
}

func (_c *Container_PruneSystem_Call) Run(run func()) *Container_PruneSystem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Container_PruneSystem_Call) Return(s string, err error) *Container_PruneSystem_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Container_PruneSystem_Call) RunAndReturn(run func() (string, error)) *Container_PruneSystem_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function for the type Container
func (_mock *Container) Pull(ctx context.Context, imageName string, options container.PullOptions) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, imageName, options)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.PullOptions) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, imageName, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.PullOptions) io.ReadCloser); ok {
		r0 = returnFunc(ctx, imageName, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, container.PullOptions) error); ok {
		r1 = returnFunc(ctx, imageName, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type Container_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName string
//   - options container.PullOptions
func (_e *Container_Expecter) Pull(ctx any, imageName any, options any) *Container_Pull_Call {
	return &Container_Pull_Call{Call: _e.mock.On("Pull", ctx, imageName, options)}
}

func (_c *Container_Pull_Call) Run(run func(ctx context.Context, imageName string, options container.PullOptions)) *Container_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.PullOptions
		if args[2] != nil {
			arg2 = args[2].(container.PullOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_Pull_Call) Return(readCloser io.ReadCloser, err error) *Container_Pull_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *Container_Pull_Call) RunAndReturn(run func(ctx context.Context, imageName string, options container.PullOptions) (io.ReadCloser, error)) *Container_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type Container
func (_mock *Container) Push(ctx context.Context, imageName string, pushOptions container.PushOptions) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, imageName, pushOptions)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.PushOptions) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, imageName, pushOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.PushOptions) io.ReadCloser); ok {
		r0 = returnFunc(ctx, imageName, pushOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, container.PushOptions) error); ok {
		r1 = returnFunc(ctx, imageName, pushOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type Container_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName string
//   - pushOptions container.PushOptions
func (_e *Container_Expecter) Push(ctx any, imageName any, pushOptions any) *Container_Push_Call {
	return &Container_Push_Call{Call: _e.mock.On("Push", ctx, imageName, pushOptions)}
}

func (_c *Container_Push_Call) Run(run func(ctx context.Context, imageName string, pushOptions container.PushOptions)) *Container_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.PushOptions
		if args[2] != nil {
			arg2 = args[2].(container.PushOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_Push_Call) Return(readCloser io.ReadCloser, err error) *Container_Push_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *Container_Push_Call) RunAndReturn(run func(ctx context.Context, imageName string, pushOptions container.PushOptions) (io.ReadCloser, error)) *Container_Push_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveContainerByID provides a mock function for the type Container
func (_mock *Container) RemoveContainerByID(ctx context.Context, containerID string, options map[string]interface{}) error {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainerByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_RemoveContainerByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContainerByID'
type Container_RemoveContainerByID_Call struct {
	*mock.Call
}

// RemoveContainerByID is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options map[string]interface{}
func (_e *Container_Expecter) RemoveContainerByID(ctx any, containerID any, options any) *Container_RemoveContainerByID_Call {
	return &Container_RemoveContainerByID_Call{Call: _e.mock.On("RemoveContainerByID", ctx, containerID, options)}
}

func (_c *Container_RemoveContainerByID_Call) Run(run func(ctx context.Context, containerID string, options map[string]interface{})) *Container_RemoveContainerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_RemoveContainerByID_Call) Return(err error) *Container_RemoveContainerByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_RemoveContainerByID_Call) RunAndReturn(run func(ctx context.Context, containerID string, options map[string]interface{}) error) *Container_RemoveContainerByID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveContainerByName provides a mock function for the type Container
func (_mock *Container) RemoveContainerByName(ctx context.Context, containerName string, options map[string]interface{}) error {
	ret := _mock.Called(ctx, containerName, options)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainerByName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, containerName, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_RemoveContainerByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContainerByName'
type Container_RemoveContainerByName_Call struct {
	*mock.Call
}

// RemoveContainerByName is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - options map[string]interface{}
func (_e *Container_Expecter) RemoveContainerByName(ctx any, containerName any, options any) *Container_RemoveContainerByName_Call {
	return &Container_RemoveContainerByName_Call{Call: _e.mock.On("RemoveContainerByName", ctx, containerName, options)}
}

func (_c *Container_RemoveContainerByName_Call) Run(run func(ctx context.Context, containerName string, options map[string]interface{})) *Container_RemoveContainerByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_RemoveContainerByName_Call) Return(err error) *Container_RemoveContainerByName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_RemoveContainerByName_Call) RunAndReturn(run func(ctx context.Context, containerName string, options map[string]interface{}) error) *Container_RemoveContainerByName_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveImage provides a mock function for the type Container
func (_mock *Container) RemoveImage(ctx context.Context, imageID string, options map[string]interface{}) error {
	ret := _mock.Called(ctx, imageID, options)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, imageID, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_RemoveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveImage'
type Container_RemoveImage_Call struct {
	*mock.Call
}

// RemoveImage is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
//   - options map[string]interface{}
func (_e *Container_Expecter) RemoveImage(ctx any, imageID any, options any) *Container_RemoveImage_Call {
	return &Container_RemoveImage_Call{Call: _e.mock.On("RemoveImage", ctx, imageID, options)}
}

func (_c *Container_RemoveImage_Call) Run(run func(ctx context.Context, imageID string, options map[string]interface{})) *Container_RemoveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_RemoveImage_Call) Return(err error) *Container_RemoveImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_RemoveImage_Call) RunAndReturn(run func(ctx context.Context, imageID string, options map[string]interface{}) error) *Container_RemoveImage_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveImageByName provides a mock function for the type Container
func (_mock *Container) RemoveImageByName(ctx context.Context, imageName string, tag string, options map[string]interface{}) error {
	ret := _mock.Called(ctx, imageName, tag, options)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImageByName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, imageName, tag, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_RemoveImageByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveImageByName'
type Container_RemoveImageByName_Call struct {
	*mock.Call
}

// RemoveImageByName is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName string
//   - tag string
//   - options map[string]interface{}
func (_e *Container_Expecter) RemoveImageByName(ctx any, imageName any, tag any, options any) *Container_RemoveImageByName_Call {
	return &Container_RemoveImageByName_Call{Call: _e.mock.On("RemoveImageByName", ctx, imageName, tag, options)}
}

func (_c *Container_RemoveImageByName_Call) Run(run func(ctx context.Context, imageName string, tag string, options map[string]interface{})) *Container_RemoveImageByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]interface{}
		if args[3] != nil {
			arg3 = args[3].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Container_RemoveImageByName_Call) Return(err error) *Container_RemoveImageByName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_RemoveImageByName_Call) RunAndReturn(run func(ctx context.Context, imageName string, tag string, options map[string]interface{}) error) *Container_RemoveImageByName_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveImagesByName provides a mock function for the type Container
func (_mock *Container) RemoveImagesByName(ctx context.Context, imageName string, options map[string]interface{}) error {
	ret := _mock.Called(ctx, imageName, options)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImagesByName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, imageName, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_RemoveImagesByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveImagesByName'
type Container_RemoveImagesByName_Call struct {
	*mock.Call
}

// RemoveImagesByName is a helper method to define mock.On call
//   - ctx context.Context
//   - imageName string
//   - options map[string]interface{}
func (_e *Container_Expecter) RemoveImagesByName(ctx any, imageName any, options any) *Container_RemoveImagesByName_Call {
	return &Container_RemoveImagesByName_Call{Call: _e.mock.On("RemoveImagesByName", ctx, imageName, options)}
}

func (_c *Container_RemoveImagesByName_Call) Run(run func(ctx context.Context, imageName string, options map[string]interface{})) *Container_RemoveImagesByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_RemoveImagesByName_Call) Return(err error) *Container_RemoveImagesByName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_RemoveImagesByName_Call) RunAndReturn(run func(ctx context.Context, imageName string, options map[string]interface{}) error) *Container_RemoveImagesByName_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveVolume provides a mock function for the type Container
func (_mock *Container) RemoveVolume(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_RemoveVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveVolume'
type Container_RemoveVolume_Call struct {
	*mock.Call
}

// RemoveVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Container_Expecter) RemoveVolume(ctx any, name any) *Container_RemoveVolume_Call {
	return &Container_RemoveVolume_Call{Call: _e.mock.On("RemoveVolume", ctx, name)}
}

func (_c *Container_RemoveVolume_Call) Run(run func(ctx context.Context, name string)) *Container_RemoveVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Container_RemoveVolume_Call) Return(err error) *Container_RemoveVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_RemoveVolume_Call) RunAndReturn(run func(ctx context.Context, name string) error) *Container_RemoveVolume_Call {
	_c.Call.Return(run)
	return _c
}

// ResizeExecContainer provides a mock function for the type Container
func (_mock *Container) ResizeExecContainer(ctx context.Context, execID string, dimension container.TtyDimension) error {
	ret := _mock.Called(ctx, execID, dimension)

	if len(ret) == 0 {
		panic("no return value specified for ResizeExecContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.TtyDimension) error); ok {
		r0 = returnFunc(ctx, execID, dimension)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_ResizeExecContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResizeExecContainer'
type Container_ResizeExecContainer_Call struct {
	*mock.Call
}

// ResizeExecContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - execID string
//   - dimension container.TtyDimension
func (_e *Container_Expecter) ResizeExecContainer(ctx any, execID any, dimension any) *Container_ResizeExecContainer_Call {
	return &Container_ResizeExecContainer_Call{Call: _e.mock.On("ResizeExecContainer", ctx, execID, dimension)}
}

func (_c *Container_ResizeExecContainer_Call) Run(run func(ctx context.Context, execID string, dimension container.TtyDimension)) *Container_ResizeExecContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.TtyDimension
		if args[2] != nil {
			arg2 = args[2].(container.TtyDimension)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_ResizeExecContainer_Call) Return(err error) *Container_ResizeExecContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_ResizeExecContainer_Call) RunAndReturn(run func(ctx context.Context, execID string, dimension container.TtyDimension) error) *Container_ResizeExecContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StartContainer provides a mock function for the type Container
func (_mock *Container) StartContainer(ctx context.Context, containerID string) error {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for StartContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_StartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContainer'
type Container_StartContainer_Call struct {
	*mock.Call
}

// StartContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *Container_Expecter) StartContainer(ctx any, containerID any) *Container_StartContainer_Call {
	return &Container_StartContainer_Call{Call: _e.mock.On("StartContainer", ctx, containerID)}
}

func (_c *Container_StartContainer_Call) Run(run func(ctx context.Context, containerID string)) *Container_StartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Container_StartContainer_Call) Return(err error) *Container_StartContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_StartContainer_Call) RunAndReturn(run func(ctx context.Context, containerID string) error) *Container_StartContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopContainerByID provides a mock function for the type Container
func (_mock *Container) StopContainerByID(ctx context.Context, containerID string, timeout time.Duration) error {
	ret := _mock.Called(ctx, containerID, timeout)

	if len(ret) == 0 {
		panic("no return value specified for StopContainerByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, containerID, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_StopContainerByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainerByID'
type Container_StopContainerByID_Call struct {
	*mock.Call
}

// StopContainerByID is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - timeout time.Duration
func (_e *Container_Expecter) StopContainerByID(ctx any, containerID any, timeout any) *Container_StopContainerByID_Call {
	return &Container_StopContainerByID_Call{Call: _e.mock.On("StopContainerByID", ctx, containerID, timeout)}
}

func (_c *Container_StopContainerByID_Call) Run(run func(ctx context.Context, containerID string, timeout time.Duration)) *Container_StopContainerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_StopContainerByID_Call) Return(err error) *Container_StopContainerByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_StopContainerByID_Call) RunAndReturn(run func(ctx context.Context, containerID string, timeout time.Duration) error) *Container_StopContainerByID_Call {
	_c.Call.Return(run)
	return _c
}

// StopContainerByName provides a mock function for the type Container
func (_mock *Container) StopContainerByName(ctx context.Context, containerName string, timeout time.Duration) error {
	ret := _mock.Called(ctx, containerName, timeout)

	if len(ret) == 0 {
		panic("no return value specified for StopContainerByName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, containerName, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_StopContainerByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainerByName'
type Container_StopContainerByName_Call struct {
	*mock.Call
}

// StopContainerByName is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - timeout time.Duration
func (_e *Container_Expecter) StopContainerByName(ctx any, containerName any, timeout any) *Container_StopContainerByName_Call {
	return &Container_StopContainerByName_Call{Call: _e.mock.On("StopContainerByName", ctx, containerName, timeout)}
}

func (_c *Container_StopContainerByName_Call) Run(run func(ctx context.Context, containerName string, timeout time.Duration)) *Container_StopContainerByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_StopContainerByName_Call) Return(err error) *Container_StopContainerByName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_StopContainerByName_Call) RunAndReturn(run func(ctx context.Context, containerName string, timeout time.Duration) error) *Container_StopContainerByName_Call {
	_c.Call.Return(run)
	return _c
}

// Tag provides a mock function for the type Container
func (_mock *Container) Tag(ctx context.Context, source string, target string) error {
	ret := _mock.Called(ctx, source, target)

	if len(ret) == 0 {
		panic("no return value specified for Tag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, source, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_Tag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tag'
type Container_Tag_Call struct {
	*mock.Call
}

// Tag is a helper method to define mock.On call
//   - ctx context.Context
//   - source string
//   - target string
func (_e *Container_Expecter) Tag(ctx any, source any, target any) *Container_Tag_Call {
	return &Container_Tag_Call{Call: _e.mock.On("Tag", ctx, source, target)}
}

func (_c *Container_Tag_Call) Run(run func(ctx context.Context, source string, target string)) *Container_Tag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_Tag_Call) Return(err error) *Container_Tag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_Tag_Call) RunAndReturn(run func(ctx context.Context, source string, target string) error) *Container_Tag_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForContainerByID provides a mock function for the type Container
func (_mock *Container) WaitForContainerByID(ctx context.Context, containerID string, condition container0.WaitCondition) (int64, error) {
	ret := _mock.Called(ctx, containerID, condition)

	if len(ret) == 0 {
		panic("no return value specified for WaitForContainerByID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container0.WaitCondition) (int64, error)); ok {
		return returnFunc(ctx, containerID, condition)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container0.WaitCondition) int64); ok {
		r0 = returnFunc(ctx, containerID, condition)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, container0.WaitCondition) error); ok {
		r1 = returnFunc(ctx, containerID, condition)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_WaitForContainerByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForContainerByID'
type Container_WaitForContainerByID_Call struct {
	*mock.Call
}

// WaitForContainerByID is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - condition container0.WaitCondition
func (_e *Container_Expecter) WaitForContainerByID(ctx any, containerID any, condition any) *Container_WaitForContainerByID_Call {
	return &Container_WaitForContainerByID_Call{Call: _e.mock.On("WaitForContainerByID", ctx, containerID, condition)}
}

func (_c *Container_WaitForContainerByID_Call) Run(run func(ctx context.Context, containerID string, condition container0.WaitCondition)) *Container_WaitForContainerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container0.WaitCondition
		if args[2] != nil {
			arg2 = args[2].(container0.WaitCondition)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_WaitForContainerByID_Call) Return(n int64, err error) *Container_WaitForContainerByID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Container_WaitForContainerByID_Call) RunAndReturn(run func(ctx context.Context, containerID string, condition container0.WaitCondition) (int64, error)) *Container_WaitForContainerByID_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForContainerByName provides a mock function for the type Container
func (_mock *Container) WaitForContainerByName(ctx context.Context, containerID string, condition container0.WaitCondition) (int64, error) {
	ret := _mock.Called(ctx, containerID, condition)

	if len(ret) == 0 {
		panic("no return value specified for WaitForContainerByName")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container0.WaitCondition) (int64, error)); ok {
		return returnFunc(ctx, containerID, condition)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container0.WaitCondition) int64); ok {
		r0 = returnFunc(ctx, containerID, condition)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, container0.WaitCondition) error); ok {
		r1 = returnFunc(ctx, containerID, condition)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_WaitForContainerByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForContainerByName'
type Container_WaitForContainerByName_Call struct {
	*mock.Call
}

// WaitForContainerByName is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - condition container0.WaitCondition
func (_e *Container_Expecter) WaitForContainerByName(ctx any, containerID any, condition any) *Container_WaitForContainerByName_Call {
	return &Container_WaitForContainerByName_Call{Call: _e.mock.On("WaitForContainerByName", ctx, containerID, condition)}
}

func (_c *Container_WaitForContainerByName_Call) Run(run func(ctx context.Context, containerID string, condition container0.WaitCondition)) *Container_WaitForContainerByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container0.WaitCondition
		if args[2] != nil {
			arg2 = args[2].(container0.WaitCondition)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_WaitForContainerByName_Call) Return(n int64, err error) *Container_WaitForContainerByName_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Container_WaitForContainerByName_Call) RunAndReturn(run func(ctx context.Context, containerID string, condition container0.WaitCondition) (int64, error)) *Container_WaitForContainerByName_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForDaemon provides a mock function for the type Container
func (_mock *Container) WaitForDaemon(retryTimeout ...time.Duration) error {
	var tmpRet mock.Arguments
	if len(retryTimeout) > 0 {
		tmpRet = _mock.Called(retryTimeout)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WaitForDaemon")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...time.Duration) error); ok {
		r0 = returnFunc(retryTimeout...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Container_WaitForDaemon_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForDaemon'
type Container_WaitForDaemon_Call struct {
	*mock.Call
}

// WaitForDaemon is a helper method to define mock.On call
//   - retryTimeout ...time.Duration
func (_e *Container_Expecter) WaitForDaemon(retryTimeout ...any) *Container_WaitForDaemon_Call {
	return &Container_WaitForDaemon_Call{Call: _e.mock.On("WaitForDaemon",
		append([]any{}, retryTimeout...)...)}
}

func (_c *Container_WaitForDaemon_Call) Run(run func(retryTimeout ...time.Duration)) *Container_WaitForDaemon_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []time.Duration
		var variadicArgs []time.Duration
		if len(args) > 0 {
			variadicArgs = args[0].([]time.Duration)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Container_WaitForDaemon_Call) Return(err error) *Container_WaitForDaemon_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Container_WaitForDaemon_Call) RunAndReturn(run func(retryTimeout ...time.Duration) error) *Container_WaitForDaemon_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForRunning provides a mock function for the type Container
func (_mock *Container) WaitForRunning(ctx context.Context, containerID string, pollingRate time.Duration) (<-chan struct{}, <-chan error) {
	ret := _mock.Called(ctx, containerID, pollingRate)

	if len(ret) == 0 {
		panic("no return value specified for WaitForRunning")
	}

	var r0 <-chan struct{}
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (<-chan struct{}, <-chan error)); ok {
		return returnFunc(ctx, containerID, pollingRate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) <-chan struct{}); ok {
		r0 = returnFunc(ctx, containerID, pollingRate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) <-chan error); ok {
		r1 = returnFunc(ctx, containerID, pollingRate)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// Container_WaitForRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForRunning'
type Container_WaitForRunning_Call struct {
	*mock.Call
}

// WaitForRunning is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - pollingRate time.Duration
func (_e *Container_Expecter) WaitForRunning(ctx any, containerID any, pollingRate any) *Container_WaitForRunning_Call {
	return &Container_WaitForRunning_Call{Call: _e.mock.On("WaitForRunning", ctx, containerID, pollingRate)}
}

func (_c *Container_WaitForRunning_Call) Run(run func(ctx context.Context, containerID string, pollingRate time.Duration)) *Container_WaitForRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Container_WaitForRunning_Call) Return(valCh <-chan struct{}, errCh <-chan error) *Container_WaitForRunning_Call {
	_c.Call.Return(valCh, errCh)
	return _c
}

func (_c *Container_WaitForRunning_Call) RunAndReturn(run func(ctx context.Context, containerID string, pollingRate time.Duration) (<-chan struct{}, <-chan error)) *Container_WaitForRunning_Call {
	_c.Call.Return(run)
	return _c
}
