// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"reagent/common"
	"reagent/messenger"
	"reagent/system"

	mock "github.com/stretchr/testify/mock"
)

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

type Database_Expecter struct {
	mock *mock.Mock
}

func (_m *Database) EXPECT() *Database_Expecter {
	return &Database_Expecter{mock: &_m.Mock}
}

// BulkUpsertRequestedStateChanges provides a mock function for the type Database
func (_mock *Database) BulkUpsertRequestedStateChanges(payloads []common.TransitionPayload) error {
	ret := _mock.Called(payloads)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsertRequestedStateChanges")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]common.TransitionPayload) error); ok {
		r0 = returnFunc(payloads)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_BulkUpsertRequestedStateChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsertRequestedStateChanges'
type Database_BulkUpsertRequestedStateChanges_Call struct {
	*mock.Call
}

// BulkUpsertRequestedStateChanges is a helper method to define mock.On call
//   - payloads []common.TransitionPayload
func (_e *Database_Expecter) BulkUpsertRequestedStateChanges(payloads any) *Database_BulkUpsertRequestedStateChanges_Call {
	return &Database_BulkUpsertRequestedStateChanges_Call{Call: _e.mock.On("BulkUpsertRequestedStateChanges", payloads)}
}

func (_c *Database_BulkUpsertRequestedStateChanges_Call) Run(run func(payloads []common.TransitionPayload)) *Database_BulkUpsertRequestedStateChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []common.TransitionPayload
		if args[0] != nil {
			arg0 = args[0].([]common.TransitionPayload)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Database_BulkUpsertRequestedStateChanges_Call) Return(err error) *Database_BulkUpsertRequestedStateChanges_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_BulkUpsertRequestedStateChanges_Call) RunAndReturn(run func(payloads []common.TransitionPayload) error) *Database_BulkUpsertRequestedStateChanges_Call {
	_c.Call.Return(run)
	return _c
}

// ClearAllLogHistory provides a mock function for the type Database
func (_mock *Database) ClearAllLogHistory(appName string, appKey uint64, stage common.Stage) error {
	ret := _mock.Called(appName, appKey, stage)

	if len(ret) == 0 {
		panic("no return value specified for ClearAllLogHistory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, uint64, common.Stage) error); ok {
		r0 = returnFunc(appName, appKey, stage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_ClearAllLogHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAllLogHistory'
type Database_ClearAllLogHistory_Call struct {
	*mock.Call
}

// ClearAllLogHistory is a helper method to define mock.On call
//   - appName string
//   - appKey uint64
//   - stage common.Stage
func (_e *Database_Expecter) ClearAllLogHistory(appName any, appKey any, stage any) *Database_ClearAllLogHistory_Call {
	return &Database_ClearAllLogHistory_Call{Call: _e.mock.On("ClearAllLogHistory", appName, appKey, stage)}
}

func (_c *Database_ClearAllLogHistory_Call) Run(run func(appName string, appKey uint64, stage common.Stage)) *Database_ClearAllLogHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 common.Stage
		if args[2] != nil {
			arg2 = args[2].(common.Stage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_ClearAllLogHistory_Call) Return(err error) *Database_ClearAllLogHistory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_ClearAllLogHistory_Call) RunAndReturn(run func(appName string, appKey uint64, stage common.Stage) error) *Database_ClearAllLogHistory_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type Database
func (_mock *Database) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Database_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Database_Expecter) Close() *Database_Close_Call {
	return &Database_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Database_Close_Call) Run(run func()) *Database_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Database_Close_Call) Return(err error) *Database_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_Close_Call) RunAndReturn(run func() error) *Database_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAppState provides a mock function for the type Database
func (_mock *Database) DeleteAppState(appKey uint64, stage common.Stage) error {
	ret := _mock.Called(appKey, stage)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAppState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, common.Stage) error); ok {
		r0 = returnFunc(appKey, stage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_DeleteAppState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAppState'
type Database_DeleteAppState_Call struct {
	*mock.Call
}

// DeleteAppState is a helper method to define mock.On call
//   - appKey uint64
//   - stage common.Stage
func (_e *Database_Expecter) DeleteAppState(appKey any, stage any) *Database_DeleteAppState_Call {
	return &Database_DeleteAppState_Call{Call: _e.mock.On("DeleteAppState", appKey, stage)}
}

func (_c *Database_DeleteAppState_Call) Run(run func(appKey uint64, stage common.Stage)) *Database_DeleteAppState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 common.Stage
		if args[1] != nil {
			arg1 = args[1].(common.Stage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_DeleteAppState_Call) Return(err error) *Database_DeleteAppState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_DeleteAppState_Call) RunAndReturn(run func(appKey uint64, stage common.Stage) error) *Database_DeleteAppState_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRequestedState provides a mock function for the type Database
func (_mock *Database) DeleteRequestedState(appKey uint64, stage common.Stage) error {
	ret := _mock.Called(appKey, stage)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRequestedState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, common.Stage) error); ok {
		r0 = returnFunc(appKey, stage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_DeleteRequestedState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRequestedState'
type Database_DeleteRequestedState_Call struct {
	*mock.Call
}

// DeleteRequestedState is a helper method to define mock.On call
//   - appKey uint64
//   - stage common.Stage
func (_e *Database_Expecter) DeleteRequestedState(appKey any, stage any) *Database_DeleteRequestedState_Call {
	return &Database_DeleteRequestedState_Call{Call: _e.mock.On("DeleteRequestedState", appKey, stage)}
}

func (_c *Database_DeleteRequestedState_Call) Run(run func(appKey uint64, stage common.Stage)) *Database_DeleteRequestedState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 common.Stage
		if args[1] != nil {
			arg1 = args[1].(common.Stage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_DeleteRequestedState_Call) Return(err error) *Database_DeleteRequestedState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_DeleteRequestedState_Call) RunAndReturn(run func(appKey uint64, stage common.Stage) error) *Database_DeleteRequestedState_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppLogHistory provides a mock function for the type Database
func (_mock *Database) GetAppLogHistory(appName string, appKey uint64, stage common.Stage) ([]string, error) {
	ret := _mock.Called(appName, appKey, stage)

	if len(ret) == 0 {
		panic("no return value specified for GetAppLogHistory")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, uint64, common.Stage) ([]string, error)); ok {
		return returnFunc(appName, appKey, stage)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uint64, common.Stage) []string); ok {
		r0 = returnFunc(appName, appKey, stage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, uint64, common.Stage) error); ok {
		r1 = returnFunc(appName, appKey, stage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetAppLogHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppLogHistory'
type Database_GetAppLogHistory_Call struct {
	*mock.Call
}

// GetAppLogHistory is a helper method to define mock.On call
//   - appName string
//   - appKey uint64
//   - stage common.Stage
func (_e *Database_Expecter) GetAppLogHistory(appName any, appKey any, stage any) *Database_GetAppLogHistory_Call {
	return &Database_GetAppLogHistory_Call{Call: _e.mock.On("GetAppLogHistory", appName, appKey, stage)}
}

func (_c *Database_GetAppLogHistory_Call) Run(run func(appName string, appKey uint64, stage common.Stage)) *Database_GetAppLogHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 common.Stage
		if args[2] != nil {
			arg2 = args[2].(common.Stage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_GetAppLogHistory_Call) Return(strings []string, err error) *Database_GetAppLogHistory_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Database_GetAppLogHistory_Call) RunAndReturn(run func(appName string, appKey uint64, stage common.Stage) ([]string, error)) *Database_GetAppLogHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppState provides a mock function for the type Database
func (_mock *Database) GetAppState(appKey uint64, stage common.Stage) (*common.App, error) {
	ret := _mock.Called(appKey, stage)

	if len(ret) == 0 {
		panic("no return value specified for GetAppState")
	}

	var r0 *common.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, common.Stage) (*common.App, error)); ok {
		return returnFunc(appKey, stage)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, common.Stage) *common.App); ok {
		r0 = returnFunc(appKey, stage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, common.Stage) error); ok {
		r1 = returnFunc(appKey, stage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetAppState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppState'
type Database_GetAppState_Call struct {
	*mock.Call
}

// GetAppState is a helper method to define mock.On call
//   - appKey uint64
//   - stage common.Stage
func (_e *Database_Expecter) GetAppState(appKey any, stage any) *Database_GetAppState_Call {
	return &Database_GetAppState_Call{Call: _e.mock.On("GetAppState", appKey, stage)}
}

func (_c *Database_GetAppState_Call) Run(run func(appKey uint64, stage common.Stage)) *Database_GetAppState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 common.Stage
		if args[1] != nil {
			arg1 = args[1].(common.Stage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_GetAppState_Call) Return(app *common.App, err error) *Database_GetAppState_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *Database_GetAppState_Call) RunAndReturn(run func(appKey uint64, stage common.Stage) (*common.App, error)) *Database_GetAppState_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppStates provides a mock function for the type Database
func (_mock *Database) GetAppStates() ([]*common.App, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAppStates")
	}

	var r0 []*common.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*common.App, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*common.App); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*common.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetAppStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppStates'
type Database_GetAppStates_Call struct {
	*mock.Call
}

// GetAppStates is a helper method to define mock.On call
func (_e *Database_Expecter) GetAppStates() *Database_GetAppStates_Call {
	return &Database_GetAppStates_Call{Call: _e.mock.On("GetAppStates")}
}

func (_c *Database_GetAppStates_Call) Run(run func()) *Database_GetAppStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Database_GetAppStates_Call) Return(apps []*common.App, err error) *Database_GetAppStates_Call {
	_c.Call.Return(apps, err)
	return _c
}

func (_c *Database_GetAppStates_Call) RunAndReturn(run func() ([]*common.App, error)) *Database_GetAppStates_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestedState provides a mock function for the type Database
func (_mock *Database) GetRequestedState(aKey uint64, aStage common.Stage) (common.TransitionPayload, error) {
	ret := _mock.Called(aKey, aStage)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestedState")
	}

	var r0 common.TransitionPayload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, common.Stage) (common.TransitionPayload, error)); ok {
		return returnFunc(aKey, aStage)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, common.Stage) common.TransitionPayload); ok {
		r0 = returnFunc(aKey, aStage)
	} else {
		r0 = ret.Get(0).(common.TransitionPayload)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, common.Stage) error); ok {
		r1 = returnFunc(aKey, aStage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetRequestedState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestedState'
type Database_GetRequestedState_Call struct {
	*mock.Call
}

// GetRequestedState is a helper method to define mock.On call
//   - aKey uint64
//   - aStage common.Stage
func (_e *Database_Expecter) GetRequestedState(aKey any, aStage any) *Database_GetRequestedState_Call {
	return &Database_GetRequestedState_Call{Call: _e.mock.On("GetRequestedState", aKey, aStage)}
}

func (_c *Database_GetRequestedState_Call) Run(run func(aKey uint64, aStage common.Stage)) *Database_GetRequestedState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 common.Stage
		if args[1] != nil {
			arg1 = args[1].(common.Stage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_GetRequestedState_Call) Return(transitionPayload common.TransitionPayload, err error) *Database_GetRequestedState_Call {
	_c.Call.Return(transitionPayload, err)
	return _c
}

func (_c *Database_GetRequestedState_Call) RunAndReturn(run func(aKey uint64, aStage common.Stage) (common.TransitionPayload, error)) *Database_GetRequestedState_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestedStates provides a mock function for the type Database
func (_mock *Database) GetRequestedStates() ([]common.TransitionPayload, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRequestedStates")
	}

	var r0 []common.TransitionPayload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]common.TransitionPayload, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []common.TransitionPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.TransitionPayload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetRequestedStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestedStates'
type Database_GetRequestedStates_Call struct {
	*mock.Call
}

// GetRequestedStates is a helper method to define mock.On call
func (_e *Database_Expecter) GetRequestedStates() *Database_GetRequestedStates_Call {
	return &Database_GetRequestedStates_Call{Call: _e.mock.On("GetRequestedStates")}
}

func (_c *Database_GetRequestedStates_Call) Run(run func()) *Database_GetRequestedStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Database_GetRequestedStates_Call) Return(transitionPayloads []common.TransitionPayload, err error) *Database_GetRequestedStates_Call {
	_c.Call.Return(transitionPayloads, err)
	return _c
}

func (_c *Database_GetRequestedStates_Call) RunAndReturn(run func() ([]common.TransitionPayload, error)) *Database_GetRequestedStates_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type Database
func (_mock *Database) Init() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type Database_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *Database_Expecter) Init() *Database_Init_Call {
	return &Database_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *Database_Init_Call) Run(run func()) *Database_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Database_Init_Call) Return(err error) *Database_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_Init_Call) RunAndReturn(run func() error) *Database_Init_Call {
	_c.Call.Return(run)
	return _c
}

// QueueTask provides a mock function for the type Database
func (_mock *Database) QueueTask(task func()) {
	_mock.Called(task)
	return
}

// Database_QueueTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueTask'
type Database_QueueTask_Call struct {
	*mock.Call
}

// QueueTask is a helper method to define mock.On call
//   - task func()
func (_e *Database_Expecter) QueueTask(task any) *Database_QueueTask_Call {
	return &Database_QueueTask_Call{Call: _e.mock.On("QueueTask", task)}
}

func (_c *Database_QueueTask_Call) Run(run func(task func())) *Database_QueueTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func()
		if args[0] != nil {
			arg0 = args[0].(func())
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Database_QueueTask_Call) Return() *Database_QueueTask_Call {
	_c.Call.Return()
	return _c
}

func (_c *Database_QueueTask_Call) RunAndReturn(run func(task func())) *Database_QueueTask_Call {
	_c.Run(run)
	return _c
}

// UpdateDeviceStatus provides a mock function for the type Database
func (_mock *Database) UpdateDeviceStatus(deviceStatus messenger.DeviceStatus) error {
	ret := _mock.Called(deviceStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeviceStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(messenger.DeviceStatus) error); ok {
		r0 = returnFunc(deviceStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateDeviceStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeviceStatus'
type Database_UpdateDeviceStatus_Call struct {
	*mock.Call
}

// UpdateDeviceStatus is a helper method to define mock.On call
//   - deviceStatus messenger.DeviceStatus
func (_e *Database_Expecter) UpdateDeviceStatus(deviceStatus any) *Database_UpdateDeviceStatus_Call {
	return &Database_UpdateDeviceStatus_Call{Call: _e.mock.On("UpdateDeviceStatus", deviceStatus)}
}

func (_c *Database_UpdateDeviceStatus_Call) Run(run func(deviceStatus messenger.DeviceStatus)) *Database_UpdateDeviceStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 messenger.DeviceStatus
		if args[0] != nil {
			arg0 = args[0].(messenger.DeviceStatus)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Database_UpdateDeviceStatus_Call) Return(err error) *Database_UpdateDeviceStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateDeviceStatus_Call) RunAndReturn(run func(deviceStatus messenger.DeviceStatus) error) *Database_UpdateDeviceStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNetworkInterface provides a mock function for the type Database
func (_mock *Database) UpdateNetworkInterface(networkInterface system.NetworkInterface) error {
	ret := _mock.Called(networkInterface)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNetworkInterface")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(system.NetworkInterface) error); ok {
		r0 = returnFunc(networkInterface)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateNetworkInterface_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNetworkInterface'
type Database_UpdateNetworkInterface_Call struct {
	*mock.Call
}

// UpdateNetworkInterface is a helper method to define mock.On call
//   - networkInterface system.NetworkInterface
func (_e *Database_Expecter) UpdateNetworkInterface(networkInterface any) *Database_UpdateNetworkInterface_Call {
	return &Database_UpdateNetworkInterface_Call{Call: _e.mock.On("UpdateNetworkInterface", networkInterface)}
}

func (_c *Database_UpdateNetworkInterface_Call) Run(run func(networkInterface system.NetworkInterface)) *Database_UpdateNetworkInterface_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 system.NetworkInterface
		if args[0] != nil {
			arg0 = args[0].(system.NetworkInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Database_UpdateNetworkInterface_Call) Return(err error) *Database_UpdateNetworkInterface_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateNetworkInterface_Call) RunAndReturn(run func(networkInterface system.NetworkInterface) error) *Database_UpdateNetworkInterface_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAppState provides a mock function for the type Database
func (_mock *Database) UpsertAppState(app *common.App, newState common.AppState) (common.Timestamp, error) {
	ret := _mock.Called(app, newState)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAppState")
	}

	var r0 common.Timestamp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*common.App, common.AppState) (common.Timestamp, error)); ok {
		return returnFunc(app, newState)
	}
	if returnFunc, ok := ret.Get(0).(func(*common.App, common.AppState) common.Timestamp); ok {
		r0 = returnFunc(app, newState)
	} else {
		r0 = ret.Get(0).(common.Timestamp)
	}
	if returnFunc, ok := ret.Get(1).(func(*common.App, common.AppState) error); ok {
		r1 = returnFunc(app, newState)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_UpsertAppState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAppState'
type Database_UpsertAppState_Call struct {
	*mock.Call
}

// UpsertAppState is a helper method to define mock.On call
//   - app *common.App
//   - newState common.AppState
func (_e *Database_Expecter) UpsertAppState(app any, newState any) *Database_UpsertAppState_Call {
	return &Database_UpsertAppState_Call{Call: _e.mock.On("UpsertAppState", app, newState)}
}

func (_c *Database_UpsertAppState_Call) Run(run func(app *common.App, newState common.AppState)) *Database_UpsertAppState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *common.App
		if args[0] != nil {
			arg0 = args[0].(*common.App)
		}
		var arg1 common.AppState
		if args[1] != nil {
			arg1 = args[1].(common.AppState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_UpsertAppState_Call) Return(timestamp common.Timestamp, err error) *Database_UpsertAppState_Call {
	_c.Call.Return(timestamp, err)
	return _c
}

func (_c *Database_UpsertAppState_Call) RunAndReturn(run func(app *common.App, newState common.AppState) (common.Timestamp, error)) *Database_UpsertAppState_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertLogHistory provides a mock function for the type Database
func (_mock *Database) UpsertLogHistory(appName string, appKey uint64, stage common.Stage, logs []string) error {
	ret := _mock.Called(appName, appKey, stage, logs)

	if len(ret) == 0 {
		panic("no return value specified for UpsertLogHistory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, uint64, common.Stage, []string) error); ok {
		r0 = returnFunc(appName, appKey, stage, logs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpsertLogHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertLogHistory'
type Database_UpsertLogHistory_Call struct {
	*mock.Call
}

// UpsertLogHistory is a helper method to define mock.On call
//   - appName string
//   - appKey uint64
//   - stage common.Stage
//   - logs []string
func (_e *Database_Expecter) UpsertLogHistory(appName any, appKey any, stage any, logs any) *Database_UpsertLogHistory_Call {
	return &Database_UpsertLogHistory_Call{Call: _e.mock.On("UpsertLogHistory", appName, appKey, stage, logs)}
}

func (_c *Database_UpsertLogHistory_Call) Run(run func(appName string, appKey uint64, stage common.Stage, logs []string)) *Database_UpsertLogHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 common.Stage
		if args[2] != nil {
			arg2 = args[2].(common.Stage)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Database_UpsertLogHistory_Call) Return(err error) *Database_UpsertLogHistory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpsertLogHistory_Call) RunAndReturn(run func(appName string, appKey uint64, stage common.Stage, logs []string) error) *Database_UpsertLogHistory_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertRequestedStateChange provides a mock function for the type Database
func (_mock *Database) UpsertRequestedStateChange(payload common.TransitionPayload) error {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for UpsertRequestedStateChange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(common.TransitionPayload) error); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpsertRequestedStateChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertRequestedStateChange'
type Database_UpsertRequestedStateChange_Call struct {
	*mock.Call
}

// UpsertRequestedStateChange is a helper method to define mock.On call
//   - payload common.TransitionPayload
func (_e *Database_Expecter) UpsertRequestedStateChange(payload any) *Database_UpsertRequestedStateChange_Call {
	return &Database_UpsertRequestedStateChange_Call{Call: _e.mock.On("UpsertRequestedStateChange", payload)}
}

func (_c *Database_UpsertRequestedStateChange_Call) Run(run func(payload common.TransitionPayload)) *Database_UpsertRequestedStateChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 common.TransitionPayload
		if args[0] != nil {
			arg0 = args[0].(common.TransitionPayload)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Database_UpsertRequestedStateChange_Call) Return(err error) *Database_UpsertRequestedStateChange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpsertRequestedStateChange_Call) RunAndReturn(run func(payload common.TransitionPayload) error) *Database_UpsertRequestedStateChange_Call {
	_c.Call.Return(run)
	return _c
}
