// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"reagent/common"
	"reagent/config"
	"reagent/messenger"
	"reagent/messenger/topics"

	mock "github.com/stretchr/testify/mock"
)

// NewMessenger creates a new instance of Messenger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessenger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Messenger {
	mock := &Messenger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Messenger is an autogenerated mock type for the Messenger type
type Messenger struct {
	mock.Mock
}

type Messenger_Expecter struct {
	mock *mock.Mock
}

func (_m *Messenger) EXPECT() *Messenger_Expecter {
	return &Messenger_Expecter{mock: &_m.Mock}
}

// Call provides a mock function for the type Messenger
func (_mock *Messenger) Call(ctx context.Context, topic topics.Topic, args []interface{}, kwargs common.Dict, options common.Dict, progCb func(messenger.Result)) (messenger.Result, error) {
	ret := _mock.Called(ctx, topic, args, kwargs, options, progCb)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 messenger.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, topics.Topic, []interface{}, common.Dict, common.Dict, func(messenger.Result)) (messenger.Result, error)); ok {
		return returnFunc(ctx, topic, args, kwargs, options, progCb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, topics.Topic, []interface{}, common.Dict, common.Dict, func(messenger.Result)) messenger.Result); ok {
		r0 = returnFunc(ctx, topic, args, kwargs, options, progCb)
	} else {
		r0 = ret.Get(0).(messenger.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, topics.Topic, []interface{}, common.Dict, common.Dict, func(messenger.Result)) error); ok {
		r1 = returnFunc(ctx, topic, args, kwargs, options, progCb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Messenger_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type Messenger_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - topic topics.Topic
//   - args []interface{}
//   - kwargs common.Dict
//   - options common.Dict
//   - progCb func(messenger.Result)
func (_e *Messenger_Expecter) Call(ctx any, topic any, args any, kwargs any, options any, progCb any) *Messenger_Call_Call {
	return &Messenger_Call_Call{Call: _e.mock.On("Call", ctx, topic, args, kwargs, options, progCb)}
}

func (_c *Messenger_Call_Call) Run(run func(ctx context.Context, topic topics.Topic, args []interface{}, kwargs common.Dict, options common.Dict, progCb func(messenger.Result))) *Messenger_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 topics.Topic
		if args[1] != nil {
			arg1 = args[1].(topics.Topic)
		}
		var arg2 []interface{}
		if args[2] != nil {
			arg2 = args[2].([]interface{})
		}
		var arg3 common.Dict
		if args[3] != nil {
			arg3 = args[3].(common.Dict)
		}
		var arg4 common.Dict
		if args[4] != nil {
			arg4 = args[4].(common.Dict)
		}
		var arg5 func(messenger.Result)
		if args[5] != nil {
			arg5 = args[5].(func(messenger.Result))
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *Messenger_Call_Call) Return(v messenger.Result, err error) *Messenger_Call_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Messenger_Call_Call) RunAndReturn(run func(ctx context.Context, topic topics.Topic, args []interface{}, kwargs common.Dict, options common.Dict, progCb func(messenger.Result)) (messenger.Result, error)) *Messenger_Call_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type Messenger
func (_mock *Messenger) Close() {
	_mock.Called()
	return
}

// Messenger_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Messenger_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Messenger_Expecter) Close() *Messenger_Close_Call {
	return &Messenger_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Messenger_Close_Call) Run(run func()) *Messenger_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Messenger_Close_Call) Return() *Messenger_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *Messenger_Close_Call) RunAndReturn(run func()) *Messenger_Close_Call {
	_c.Run(run)
	return _c
}

// Connected provides a mock function for the type Messenger
func (_mock *Messenger) Connected() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connected")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Messenger_Connected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connected'
type Messenger_Connected_Call struct {
	*mock.Call
}

// Connected is a helper method to define mock.On call
func (_e *Messenger_Expecter) Connected() *Messenger_Connected_Call {
	return &Messenger_Connected_Call{Call: _e.mock.On("Connected")}
}

func (_c *Messenger_Connected_Call) Run(run func()) *Messenger_Connected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Messenger_Connected_Call) Return(b bool) *Messenger_Connected_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Messenger_Connected_Call) RunAndReturn(run func() bool) *Messenger_Connected_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type Messenger
func (_mock *Messenger) GetConfig() *config.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *config.Config
	if returnFunc, ok := ret.Get(0).(func() *config.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Config)
		}
	}
	return r0
}

// Messenger_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type Messenger_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *Messenger_Expecter) GetConfig() *Messenger_GetConfig_Call {
	return &Messenger_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *Messenger_GetConfig_Call) Run(run func()) *Messenger_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Messenger_GetConfig_Call) Return(config1 *config.Config) *Messenger_GetConfig_Call {
	_c.Call.Return(config1)
	return _c
}

func (_c *Messenger_GetConfig_Call) RunAndReturn(run func() *config.Config) *Messenger_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionID provides a mock function for the type Messenger
func (_mock *Messenger) GetSessionID() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSessionID")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// Messenger_GetSessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionID'
type Messenger_GetSessionID_Call struct {
	*mock.Call
}

// GetSessionID is a helper method to define mock.On call
func (_e *Messenger_Expecter) GetSessionID() *Messenger_GetSessionID_Call {
	return &Messenger_GetSessionID_Call{Call: _e.mock.On("GetSessionID")}
}

func (_c *Messenger_GetSessionID_Call) Run(run func()) *Messenger_GetSessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Messenger_GetSessionID_Call) Return(v uint64) *Messenger_GetSessionID_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Messenger_GetSessionID_Call) RunAndReturn(run func() uint64) *Messenger_GetSessionID_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type Messenger
func (_mock *Messenger) Publish(topic topics.Topic, args []interface{}, kwargs common.Dict, options common.Dict) error {
	ret := _mock.Called(topic, args, kwargs, options)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(topics.Topic, []interface{}, common.Dict, common.Dict) error); ok {
		r0 = returnFunc(topic, args, kwargs, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Messenger_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Messenger_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - topic topics.Topic
//   - args []interface{}
//   - kwargs common.Dict
//   - options common.Dict
func (_e *Messenger_Expecter) Publish(topic any, args any, kwargs any, options any) *Messenger_Publish_Call {
	return &Messenger_Publish_Call{Call: _e.mock.On("Publish", topic, args, kwargs, options)}
}

func (_c *Messenger_Publish_Call) Run(run func(topic topics.Topic, args []interface{}, kwargs common.Dict, options common.Dict)) *Messenger_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 topics.Topic
		if args[0] != nil {
			arg0 = args[0].(topics.Topic)
		}
		var arg1 []interface{}
		if args[1] != nil {
			arg1 = args[1].([]interface{})
		}
		var arg2 common.Dict
		if args[2] != nil {
			arg2 = args[2].(common.Dict)
		}
		var arg3 common.Dict
		if args[3] != nil {
			arg3 = args[3].(common.Dict)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Messenger_Publish_Call) Return(err error) *Messenger_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Messenger_Publish_Call) RunAndReturn(run func(topic topics.Topic, args []interface{}, kwargs common.Dict, options common.Dict) error) *Messenger_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type Messenger
func (_mock *Messenger) Register(topic topics.Topic, cb func(ctx context.Context, invocation messenger.Result) (*messenger.InvokeResult, error), options common.Dict) error {
	ret := _mock.Called(topic, cb, options)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(topics.Topic, func(ctx context.Context, invocation messenger.Result) (*messenger.InvokeResult, error), common.Dict) error); ok {
		r0 = returnFunc(topic, cb, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Messenger_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Messenger_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - topic topics.Topic
//   - cb func(ctx context.Context, invocation messenger.Result) (*messenger.InvokeResult, error)
//   - options common.Dict
func (_e *Messenger_Expecter) Register(topic any, cb any, options any) *Messenger_Register_Call {
	return &Messenger_Register_Call{Call: _e.mock.On("Register", topic, cb, options)}
}

func (_c *Messenger_Register_Call) Run(run func(topic topics.Topic, cb func(ctx context.Context, invocation messenger.Result) (*messenger.InvokeResult, error), options common.Dict)) *Messenger_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 topics.Topic
		if args[0] != nil {
			arg0 = args[0].(topics.Topic)
		}
		var arg1 func(ctx context.Context, invocation messenger.Result) (*messenger.InvokeResult, error)
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, invocation messenger.Result) (*messenger.InvokeResult, error))
		}
		var arg2 common.Dict
		if args[2] != nil {
			arg2 = args[2].(common.Dict)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Messenger_Register_Call) Return(err error) *Messenger_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Messenger_Register_Call) RunAndReturn(run func(topic topics.Topic, cb func(ctx context.Context, invocation messenger.Result) (*messenger.InvokeResult, error), options common.Dict) error) *Messenger_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RegistrationID provides a mock function for the type Messenger
func (_mock *Messenger) RegistrationID(topic topics.Topic) (uint64, bool) {
	ret := _mock.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for RegistrationID")
	}

	var r0 uint64
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(topics.Topic) (uint64, bool)); ok {
		return returnFunc(topic)
	}
	if returnFunc, ok := ret.Get(0).(func(topics.Topic) uint64); ok {
		r0 = returnFunc(topic)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(topics.Topic) bool); ok {
		r1 = returnFunc(topic)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// Messenger_RegistrationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegistrationID'
type Messenger_RegistrationID_Call struct {
	*mock.Call
}

// RegistrationID is a helper method to define mock.On call
//   - topic topics.Topic
func (_e *Messenger_Expecter) RegistrationID(topic any) *Messenger_RegistrationID_Call {
	return &Messenger_RegistrationID_Call{Call: _e.mock.On("RegistrationID", topic)}
}

func (_c *Messenger_RegistrationID_Call) Run(run func(topic topics.Topic)) *Messenger_RegistrationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 topics.Topic
		if args[0] != nil {
			arg0 = args[0].(topics.Topic)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Messenger_RegistrationID_Call) Return(id uint64, ok bool) *Messenger_RegistrationID_Call {
	_c.Call.Return(id, ok)
	return _c
}

func (_c *Messenger_RegistrationID_Call) RunAndReturn(run func(topic topics.Topic) (uint64, bool)) *Messenger_RegistrationID_Call {
	_c.Call.Return(run)
	return _c
}

// SetOnConnect provides a mock function for the type Messenger
func (_mock *Messenger) SetOnConnect(cb func(reconnect bool)) {
	_mock.Called(cb)
	return
}

// Messenger_SetOnConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnConnect'
type Messenger_SetOnConnect_Call struct {
	*mock.Call
}

// SetOnConnect is a helper method to define mock.On call
//   - cb func(reconnect bool)
func (_e *Messenger_Expecter) SetOnConnect(cb any) *Messenger_SetOnConnect_Call {
	return &Messenger_SetOnConnect_Call{Call: _e.mock.On("SetOnConnect", cb)}
}

func (_c *Messenger_SetOnConnect_Call) Run(run func(cb func(reconnect bool))) *Messenger_SetOnConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(reconnect bool)
		if args[0] != nil {
			arg0 = args[0].(func(reconnect bool))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Messenger_SetOnConnect_Call) Return() *Messenger_SetOnConnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *Messenger_SetOnConnect_Call) RunAndReturn(run func(cb func(reconnect bool))) *Messenger_SetOnConnect_Call {
	_c.Run(run)
	return _c
}

// SetupTestament provides a mock function for the type Messenger
func (_mock *Messenger) SetupTestament() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SetupTestament")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Messenger_SetupTestament_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupTestament'
type Messenger_SetupTestament_Call struct {
	*mock.Call
}

// SetupTestament is a helper method to define mock.On call
func (_e *Messenger_Expecter) SetupTestament() *Messenger_SetupTestament_Call {
	return &Messenger_SetupTestament_Call{Call: _e.mock.On("SetupTestament")}
}

func (_c *Messenger_SetupTestament_Call) Run(run func()) *Messenger_SetupTestament_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Messenger_SetupTestament_Call) Return(err error) *Messenger_SetupTestament_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Messenger_SetupTestament_Call) RunAndReturn(run func() error) *Messenger_SetupTestament_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type Messenger
func (_mock *Messenger) Subscribe(topic topics.Topic, cb func(messenger.Result) error, options common.Dict) error {
	ret := _mock.Called(topic, cb, options)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(topics.Topic, func(messenger.Result) error, common.Dict) error); ok {
		r0 = returnFunc(topic, cb, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Messenger_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type Messenger_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topic topics.Topic
//   - cb func(messenger.Result) error
//   - options common.Dict
func (_e *Messenger_Expecter) Subscribe(topic any, cb any, options any) *Messenger_Subscribe_Call {
	return &Messenger_Subscribe_Call{Call: _e.mock.On("Subscribe", topic, cb, options)}
}

func (_c *Messenger_Subscribe_Call) Run(run func(topic topics.Topic, cb func(messenger.Result) error, options common.Dict)) *Messenger_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 topics.Topic
		if args[0] != nil {
			arg0 = args[0].(topics.Topic)
		}
		var arg1 func(messenger.Result) error
		if args[1] != nil {
			arg1 = args[1].(func(messenger.Result) error)
		}
		var arg2 common.Dict
		if args[2] != nil {
			arg2 = args[2].(common.Dict)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Messenger_Subscribe_Call) Return(err error) *Messenger_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Messenger_Subscribe_Call) RunAndReturn(run func(topic topics.Topic, cb func(messenger.Result) error, options common.Dict) error) *Messenger_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// SubscriptionID provides a mock function for the type Messenger
func (_mock *Messenger) SubscriptionID(topic topics.Topic) (uint64, bool) {
	ret := _mock.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for SubscriptionID")
	}

	var r0 uint64
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(topics.Topic) (uint64, bool)); ok {
		return returnFunc(topic)
	}
	if returnFunc, ok := ret.Get(0).(func(topics.Topic) uint64); ok {
		r0 = returnFunc(topic)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(topics.Topic) bool); ok {
		r1 = returnFunc(topic)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// Messenger_SubscriptionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscriptionID'
type Messenger_SubscriptionID_Call struct {
	*mock.Call
}

// SubscriptionID is a helper method to define mock.On call
//   - topic topics.Topic
func (_e *Messenger_Expecter) SubscriptionID(topic any) *Messenger_SubscriptionID_Call {
	return &Messenger_SubscriptionID_Call{Call: _e.mock.On("SubscriptionID", topic)}
}

func (_c *Messenger_SubscriptionID_Call) Run(run func(topic topics.Topic)) *Messenger_SubscriptionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 topics.Topic
		if args[0] != nil {
			arg0 = args[0].(topics.Topic)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Messenger_SubscriptionID_Call) Return(id uint64, ok bool) *Messenger_SubscriptionID_Call {
	_c.Call.Return(id, ok)
	return _c
}

func (_c *Messenger_SubscriptionID_Call) RunAndReturn(run func(topic topics.Topic) (uint64, bool)) *Messenger_SubscriptionID_Call {
	_c.Call.Return(run)
	return _c
}

// Unregister provides a mock function for the type Messenger
func (_mock *Messenger) Unregister(topic topics.Topic) error {
	ret := _mock.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for Unregister")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(topics.Topic) error); ok {
		r0 = returnFunc(topic)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Messenger_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type Messenger_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - topic topics.Topic
func (_e *Messenger_Expecter) Unregister(topic any) *Messenger_Unregister_Call {
	return &Messenger_Unregister_Call{Call: _e.mock.On("Unregister", topic)}
}

func (_c *Messenger_Unregister_Call) Run(run func(topic topics.Topic)) *Messenger_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 topics.Topic
		if args[0] != nil {
			arg0 = args[0].(topics.Topic)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Messenger_Unregister_Call) Return(err error) *Messenger_Unregister_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Messenger_Unregister_Call) RunAndReturn(run func(topic topics.Topic) error) *Messenger_Unregister_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type Messenger
func (_mock *Messenger) Unsubscribe(topic topics.Topic) error {
	ret := _mock.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(topics.Topic) error); ok {
		r0 = returnFunc(topic)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Messenger_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type Messenger_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - topic topics.Topic
func (_e *Messenger_Expecter) Unsubscribe(topic any) *Messenger_Unsubscribe_Call {
	return &Messenger_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", topic)}
}

func (_c *Messenger_Unsubscribe_Call) Run(run func(topic topics.Topic)) *Messenger_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 topics.Topic
		if args[0] != nil {
			arg0 = args[0].(topics.Topic)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Messenger_Unsubscribe_Call) Return(err error) *Messenger_Unsubscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Messenger_Unsubscribe_Call) RunAndReturn(run func(topic topics.Topic) error) *Messenger_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRemoteDeviceStatus provides a mock function for the type Messenger
func (_mock *Messenger) UpdateRemoteDeviceStatus(status messenger.DeviceStatus) error {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRemoteDeviceStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(messenger.DeviceStatus) error); ok {
		r0 = returnFunc(status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Messenger_UpdateRemoteDeviceStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRemoteDeviceStatus'
type Messenger_UpdateRemoteDeviceStatus_Call struct {
	*mock.Call
}

// UpdateRemoteDeviceStatus is a helper method to define mock.On call
//   - status messenger.DeviceStatus
func (_e *Messenger_Expecter) UpdateRemoteDeviceStatus(status any) *Messenger_UpdateRemoteDeviceStatus_Call {
	return &Messenger_UpdateRemoteDeviceStatus_Call{Call: _e.mock.On("UpdateRemoteDeviceStatus", status)}
}

func (_c *Messenger_UpdateRemoteDeviceStatus_Call) Run(run func(status messenger.DeviceStatus)) *Messenger_UpdateRemoteDeviceStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 messenger.DeviceStatus
		if args[0] != nil {
			arg0 = args[0].(messenger.DeviceStatus)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Messenger_UpdateRemoteDeviceStatus_Call) Return(err error) *Messenger_UpdateRemoteDeviceStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Messenger_UpdateRemoteDeviceStatus_Call) RunAndReturn(run func(status messenger.DeviceStatus) error) *Messenger_UpdateRemoteDeviceStatus_Call {
	_c.Call.Return(run)
	return _c
}
