// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"reagent/network"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewNetwork creates a new instance of Network. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetwork(t interface {
	mock.TestingT
	Cleanup(func())
}) *Network {
	mock := &Network{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Network is an autogenerated mock type for the Network type
type Network struct {
	mock.Mock
}

type Network_Expecter struct {
	mock *mock.Mock
}

func (_m *Network) EXPECT() *Network_Expecter {
	return &Network_Expecter{mock: &_m.Mock}
}

// ActivateWiFi provides a mock function for the type Network
func (_mock *Network) ActivateWiFi(mac string, ssid string) error {
	ret := _mock.Called(mac, ssid)

	if len(ret) == 0 {
		panic("no return value specified for ActivateWiFi")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(mac, ssid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Network_ActivateWiFi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateWiFi'
type Network_ActivateWiFi_Call struct {
	*mock.Call
}

// ActivateWiFi is a helper method to define mock.On call
//   - mac string
//   - ssid string
func (_e *Network_Expecter) ActivateWiFi(mac any, ssid any) *Network_ActivateWiFi_Call {
	return &Network_ActivateWiFi_Call{Call: _e.mock.On("ActivateWiFi", mac, ssid)}
}

func (_c *Network_ActivateWiFi_Call) Run(run func(mac string, ssid string)) *Network_ActivateWiFi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Network_ActivateWiFi_Call) Return(err error) *Network_ActivateWiFi_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Network_ActivateWiFi_Call) RunAndReturn(run func(mac string, ssid string) error) *Network_ActivateWiFi_Call {
	_c.Call.Return(run)
	return _c
}

// AddWiFi provides a mock function for the type Network
func (_mock *Network) AddWiFi(mac string, credentials network.WiFiCredentials) error {
	ret := _mock.Called(mac, credentials)

	if len(ret) == 0 {
		panic("no return value specified for AddWiFi")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, network.WiFiCredentials) error); ok {
		r0 = returnFunc(mac, credentials)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Network_AddWiFi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWiFi'
type Network_AddWiFi_Call struct {
	*mock.Call
}

// AddWiFi is a helper method to define mock.On call
//   - mac string
//   - credentials network.WiFiCredentials
func (_e *Network_Expecter) AddWiFi(mac any, credentials any) *Network_AddWiFi_Call {
	return &Network_AddWiFi_Call{Call: _e.mock.On("AddWiFi", mac, credentials)}
}

func (_c *Network_AddWiFi_Call) Run(run func(mac string, credentials network.WiFiCredentials)) *Network_AddWiFi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 network.WiFiCredentials
		if args[1] != nil {
			arg1 = args[1].(network.WiFiCredentials)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Network_AddWiFi_Call) Return(err error) *Network_AddWiFi_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Network_AddWiFi_Call) RunAndReturn(run func(mac string, credentials network.WiFiCredentials) error) *Network_AddWiFi_Call {
	_c.Call.Return(run)
	return _c
}

// EnableDHCP provides a mock function for the type Network
func (_mock *Network) EnableDHCP(mac string, interfaceName string) error {
	ret := _mock.Called(mac, interfaceName)

	if len(ret) == 0 {
		panic("no return value specified for EnableDHCP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(mac, interfaceName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Network_EnableDHCP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableDHCP'
type Network_EnableDHCP_Call struct {
	*mock.Call
}

// EnableDHCP is a helper method to define mock.On call
//   - mac string
//   - interfaceName string
func (_e *Network_Expecter) EnableDHCP(mac any, interfaceName any) *Network_EnableDHCP_Call {
	return &Network_EnableDHCP_Call{Call: _e.mock.On("EnableDHCP", mac, interfaceName)}
}

func (_c *Network_EnableDHCP_Call) Run(run func(mac string, interfaceName string)) *Network_EnableDHCP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Network_EnableDHCP_Call) Return(err error) *Network_EnableDHCP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Network_EnableDHCP_Call) RunAndReturn(run func(mac string, interfaceName string) error) *Network_EnableDHCP_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveWirelessDeviceConfig provides a mock function for the type Network
func (_mock *Network) GetActiveWirelessDeviceConfig() ([]network.IPv4AddressData, []network.IPv6AddressData, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActiveWirelessDeviceConfig")
	}

	var r0 []network.IPv4AddressData
	var r1 []network.IPv6AddressData
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() ([]network.IPv4AddressData, []network.IPv6AddressData, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []network.IPv4AddressData); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]network.IPv4AddressData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() []network.IPv6AddressData); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]network.IPv6AddressData)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Network_GetActiveWirelessDeviceConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveWirelessDeviceConfig'
type Network_GetActiveWirelessDeviceConfig_Call struct {
	*mock.Call
}

// GetActiveWirelessDeviceConfig is a helper method to define mock.On call
func (_e *Network_Expecter) GetActiveWirelessDeviceConfig() *Network_GetActiveWirelessDeviceConfig_Call {
	return &Network_GetActiveWirelessDeviceConfig_Call{Call: _e.mock.On("GetActiveWirelessDeviceConfig")}
}

func (_c *Network_GetActiveWirelessDeviceConfig_Call) Run(run func()) *Network_GetActiveWirelessDeviceConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Network_GetActiveWirelessDeviceConfig_Call) Return(iPv4AddressDatas []network.IPv4AddressData, iPv6AddressDatas []network.IPv6AddressData, err error) *Network_GetActiveWirelessDeviceConfig_Call {
	_c.Call.Return(iPv4AddressDatas, iPv6AddressDatas, err)
	return _c
}

func (_c *Network_GetActiveWirelessDeviceConfig_Call) RunAndReturn(run func() ([]network.IPv4AddressData, []network.IPv6AddressData, error)) *Network_GetActiveWirelessDeviceConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ListEthernetDevices provides a mock function for the type Network
func (_mock *Network) ListEthernetDevices() ([]network.EthernetDevice, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListEthernetDevices")
	}

	var r0 []network.EthernetDevice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]network.EthernetDevice, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []network.EthernetDevice); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]network.EthernetDevice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Network_ListEthernetDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEthernetDevices'
type Network_ListEthernetDevices_Call struct {
	*mock.Call
}

// ListEthernetDevices is a helper method to define mock.On call
func (_e *Network_Expecter) ListEthernetDevices() *Network_ListEthernetDevices_Call {
	return &Network_ListEthernetDevices_Call{Call: _e.mock.On("ListEthernetDevices")}
}

func (_c *Network_ListEthernetDevices_Call) Run(run func()) *Network_ListEthernetDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Network_ListEthernetDevices_Call) Return(ethernetDevices []network.EthernetDevice, err error) *Network_ListEthernetDevices_Call {
	_c.Call.Return(ethernetDevices, err)
	return _c
}

func (_c *Network_ListEthernetDevices_Call) RunAndReturn(run func() ([]network.EthernetDevice, error)) *Network_ListEthernetDevices_Call {
	_c.Call.Return(run)
	return _c
}

// ListWifiNetworks provides a mock function for the type Network
func (_mock *Network) ListWifiNetworks() ([]network.WiFi, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListWifiNetworks")
	}

	var r0 []network.WiFi
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]network.WiFi, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []network.WiFi); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]network.WiFi)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Network_ListWifiNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWifiNetworks'
type Network_ListWifiNetworks_Call struct {
	*mock.Call
}

// ListWifiNetworks is a helper method to define mock.On call
func (_e *Network_Expecter) ListWifiNetworks() *Network_ListWifiNetworks_Call {
	return &Network_ListWifiNetworks_Call{Call: _e.mock.On("ListWifiNetworks")}
}

func (_c *Network_ListWifiNetworks_Call) Run(run func()) *Network_ListWifiNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Network_ListWifiNetworks_Call) Return(wiFis []network.WiFi, err error) *Network_ListWifiNetworks_Call {
	_c.Call.Return(wiFis, err)
	return _c
}

func (_c *Network_ListWifiNetworks_Call) RunAndReturn(run func() ([]network.WiFi, error)) *Network_ListWifiNetworks_Call {
	_c.Call.Return(run)
	return _c
}

// Reload provides a mock function for the type Network
func (_mock *Network) Reload() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Network_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type Network_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
func (_e *Network_Expecter) Reload() *Network_Reload_Call {
	return &Network_Reload_Call{Call: _e.mock.On("Reload")}
}

func (_c *Network_Reload_Call) Run(run func()) *Network_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Network_Reload_Call) Return(err error) *Network_Reload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Network_Reload_Call) RunAndReturn(run func() error) *Network_Reload_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveWifi provides a mock function for the type Network
func (_mock *Network) RemoveWifi(ssid string) error {
	ret := _mock.Called(ssid)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWifi")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(ssid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Network_RemoveWifi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveWifi'
type Network_RemoveWifi_Call struct {
	*mock.Call
}

// RemoveWifi is a helper method to define mock.On call
//   - ssid string
func (_e *Network_Expecter) RemoveWifi(ssid any) *Network_RemoveWifi_Call {
	return &Network_RemoveWifi_Call{Call: _e.mock.On("RemoveWifi", ssid)}
}

func (_c *Network_RemoveWifi_Call) Run(run func(ssid string)) *Network_RemoveWifi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Network_RemoveWifi_Call) Return(err error) *Network_RemoveWifi_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Network_RemoveWifi_Call) RunAndReturn(run func(ssid string) error) *Network_RemoveWifi_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type Network
func (_mock *Network) Scan(timeoutParam ...time.Duration) error {
	var tmpRet mock.Arguments
	if len(timeoutParam) > 0 {
		tmpRet = _mock.Called(timeoutParam)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...time.Duration) error); ok {
		r0 = returnFunc(timeoutParam...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Network_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type Network_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - timeoutParam ...time.Duration
func (_e *Network_Expecter) Scan(timeoutParam ...any) *Network_Scan_Call {
	return &Network_Scan_Call{Call: _e.mock.On("Scan",
		append([]any{}, timeoutParam...)...)}
}

func (_c *Network_Scan_Call) Run(run func(timeoutParam ...time.Duration)) *Network_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []time.Duration
		var variadicArgs []time.Duration
		if len(args) > 0 {
			variadicArgs = args[0].([]time.Duration)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Network_Scan_Call) Return(err error) *Network_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Network_Scan_Call) RunAndReturn(run func(timeoutParam ...time.Duration) error) *Network_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// SetIPv4Address provides a mock function for the type Network
func (_mock *Network) SetIPv4Address(mac string, interfaceName string, ip string, prefix uint32) error {
	ret := _mock.Called(mac, interfaceName, ip, prefix)

	if len(ret) == 0 {
		panic("no return value specified for SetIPv4Address")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, uint32) error); ok {
		r0 = returnFunc(mac, interfaceName, ip, prefix)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Network_SetIPv4Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIPv4Address'
type Network_SetIPv4Address_Call struct {
	*mock.Call
}

// SetIPv4Address is a helper method to define mock.On call
//   - mac string
//   - interfaceName string
//   - ip string
//   - prefix uint32
func (_e *Network_Expecter) SetIPv4Address(mac any, interfaceName any, ip any, prefix any) *Network_SetIPv4Address_Call {
	return &Network_SetIPv4Address_Call{Call: _e.mock.On("SetIPv4Address", mac, interfaceName, ip, prefix)}
}

func (_c *Network_SetIPv4Address_Call) Run(run func(mac string, interfaceName string, ip string, prefix uint32)) *Network_SetIPv4Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uint32
		if args[3] != nil {
			arg3 = args[3].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Network_SetIPv4Address_Call) Return(err error) *Network_SetIPv4Address_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Network_SetIPv4Address_Call) RunAndReturn(run func(mac string, interfaceName string, ip string, prefix uint32) error) *Network_SetIPv4Address_Call {
	_c.Call.Return(run)
	return _c
}
