// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"reagent/common"
	"reagent/tunnel"

	mock "github.com/stretchr/testify/mock"
)

// NewTunnelManager creates a new instance of TunnelManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTunnelManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TunnelManager {
	mock := &TunnelManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TunnelManager is an autogenerated mock type for the TunnelManager type
type TunnelManager struct {
	mock.Mock
}

type TunnelManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TunnelManager) EXPECT() *TunnelManager_Expecter {
	return &TunnelManager_Expecter{mock: &_m.Mock}
}

// AddTunnel provides a mock function for the type TunnelManager
func (_mock *TunnelManager) AddTunnel(config tunnel.TunnelConfig) (tunnel.TunnelConfig, error) {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for AddTunnel")
	}

	var r0 tunnel.TunnelConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(tunnel.TunnelConfig) (tunnel.TunnelConfig, error)); ok {
		return returnFunc(config)
	}
	if returnFunc, ok := ret.Get(0).(func(tunnel.TunnelConfig) tunnel.TunnelConfig); ok {
		r0 = returnFunc(config)
	} else {
		r0 = ret.Get(0).(tunnel.TunnelConfig)
	}
	if returnFunc, ok := ret.Get(1).(func(tunnel.TunnelConfig) error); ok {
		r1 = returnFunc(config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TunnelManager_AddTunnel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTunnel'
type TunnelManager_AddTunnel_Call struct {
	*mock.Call
}

// AddTunnel is a helper method to define mock.On call
//   - config tunnel.TunnelConfig
func (_e *TunnelManager_Expecter) AddTunnel(config any) *TunnelManager_AddTunnel_Call {
	return &TunnelManager_AddTunnel_Call{Call: _e.mock.On("AddTunnel", config)}
}

func (_c *TunnelManager_AddTunnel_Call) Run(run func(config tunnel.TunnelConfig)) *TunnelManager_AddTunnel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tunnel.TunnelConfig
		if args[0] != nil {
			arg0 = args[0].(tunnel.TunnelConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TunnelManager_AddTunnel_Call) Return(tunnelConfig tunnel.TunnelConfig, err error) *TunnelManager_AddTunnel_Call {
	_c.Call.Return(tunnelConfig, err)
	return _c
}

func (_c *TunnelManager_AddTunnel_Call) RunAndReturn(run func(config tunnel.TunnelConfig) (tunnel.TunnelConfig, error)) *TunnelManager_AddTunnel_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TunnelManager
func (_mock *TunnelManager) Get(tunnelID string) *tunnel.Tunnel {
	ret := _mock.Called(tunnelID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *tunnel.Tunnel
	if returnFunc, ok := ret.Get(0).(func(string) *tunnel.Tunnel); ok {
		r0 = returnFunc(tunnelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tunnel.Tunnel)
		}
	}
	return r0
}

// TunnelManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TunnelManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - tunnelID string
func (_e *TunnelManager_Expecter) Get(tunnelID any) *TunnelManager_Get_Call {
	return &TunnelManager_Get_Call{Call: _e.mock.On("Get", tunnelID)}
}

func (_c *TunnelManager_Get_Call) Run(run func(tunnelID string)) *TunnelManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TunnelManager_Get_Call) Return(tunnel1 *tunnel.Tunnel) *TunnelManager_Get_Call {
	_c.Call.Return(tunnel1)
	return _c
}

func (_c *TunnelManager_Get_Call) RunAndReturn(run func(tunnelID string) *tunnel.Tunnel) *TunnelManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function for the type TunnelManager
func (_mock *TunnelManager) GetState() ([]tunnel.TunnelState, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 []tunnel.TunnelState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]tunnel.TunnelState, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []tunnel.TunnelState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tunnel.TunnelState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TunnelManager_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type TunnelManager_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
func (_e *TunnelManager_Expecter) GetState() *TunnelManager_GetState_Call {
	return &TunnelManager_GetState_Call{Call: _e.mock.On("GetState")}
}

func (_c *TunnelManager_GetState_Call) Run(run func()) *TunnelManager_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TunnelManager_GetState_Call) Return(tunnelStates []tunnel.TunnelState, err error) *TunnelManager_GetState_Call {
	_c.Call.Return(tunnelStates, err)
	return _c
}

func (_c *TunnelManager_GetState_Call) RunAndReturn(run func() ([]tunnel.TunnelState, error)) *TunnelManager_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// GetStateById provides a mock function for the type TunnelManager
func (_mock *TunnelManager) GetStateById(tunnelID string) (tunnel.TunnelState, error) {
	ret := _mock.Called(tunnelID)

	if len(ret) == 0 {
		panic("no return value specified for GetStateById")
	}

	var r0 tunnel.TunnelState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (tunnel.TunnelState, error)); ok {
		return returnFunc(tunnelID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) tunnel.TunnelState); ok {
		r0 = returnFunc(tunnelID)
	} else {
		r0 = ret.Get(0).(tunnel.TunnelState)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tunnelID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TunnelManager_GetStateById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStateById'
type TunnelManager_GetStateById_Call struct {
	*mock.Call
}

// GetStateById is a helper method to define mock.On call
//   - tunnelID string
func (_e *TunnelManager_Expecter) GetStateById(tunnelID any) *TunnelManager_GetStateById_Call {
	return &TunnelManager_GetStateById_Call{Call: _e.mock.On("GetStateById", tunnelID)}
}

func (_c *TunnelManager_GetStateById_Call) Run(run func(tunnelID string)) *TunnelManager_GetStateById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TunnelManager_GetStateById_Call) Return(tunnelState tunnel.TunnelState, err error) *TunnelManager_GetStateById_Call {
	_c.Call.Return(tunnelState, err)
	return _c
}

func (_c *TunnelManager_GetStateById_Call) RunAndReturn(run func(tunnelID string) (tunnel.TunnelState, error)) *TunnelManager_GetStateById_Call {
	_c.Call.Return(run)
	return _c
}

// GetTunnelConfig provides a mock function for the type TunnelManager
func (_mock *TunnelManager) GetTunnelConfig() ([]tunnel.TunnelConfig, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTunnelConfig")
	}

	var r0 []tunnel.TunnelConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]tunnel.TunnelConfig, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []tunnel.TunnelConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tunnel.TunnelConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TunnelManager_GetTunnelConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTunnelConfig'
type TunnelManager_GetTunnelConfig_Call struct {
	*mock.Call
}

// GetTunnelConfig is a helper method to define mock.On call
func (_e *TunnelManager_Expecter) GetTunnelConfig() *TunnelManager_GetTunnelConfig_Call {
	return &TunnelManager_GetTunnelConfig_Call{Call: _e.mock.On("GetTunnelConfig")}
}

func (_c *TunnelManager_GetTunnelConfig_Call) Run(run func()) *TunnelManager_GetTunnelConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TunnelManager_GetTunnelConfig_Call) Return(tunnelConfigs []tunnel.TunnelConfig, err error) *TunnelManager_GetTunnelConfig_Call {
	_c.Call.Return(tunnelConfigs, err)
	return _c
}

func (_c *TunnelManager_GetTunnelConfig_Call) RunAndReturn(run func() ([]tunnel.TunnelConfig, error)) *TunnelManager_GetTunnelConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Reload provides a mock function for the type TunnelManager
func (_mock *TunnelManager) Reload() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TunnelManager_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type TunnelManager_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
func (_e *TunnelManager_Expecter) Reload() *TunnelManager_Reload_Call {
	return &TunnelManager_Reload_Call{Call: _e.mock.On("Reload")}
}

func (_c *TunnelManager_Reload_Call) Run(run func()) *TunnelManager_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TunnelManager_Reload_Call) Return(err error) *TunnelManager_Reload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TunnelManager_Reload_Call) RunAndReturn(run func() error) *TunnelManager_Reload_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTunnel provides a mock function for the type TunnelManager
func (_mock *TunnelManager) RemoveTunnel(conf tunnel.TunnelConfig) error {
	ret := _mock.Called(conf)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTunnel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(tunnel.TunnelConfig) error); ok {
		r0 = returnFunc(conf)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TunnelManager_RemoveTunnel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTunnel'
type TunnelManager_RemoveTunnel_Call struct {
	*mock.Call
}

// RemoveTunnel is a helper method to define mock.On call
//   - conf tunnel.TunnelConfig
func (_e *TunnelManager_Expecter) RemoveTunnel(conf any) *TunnelManager_RemoveTunnel_Call {
	return &TunnelManager_RemoveTunnel_Call{Call: _e.mock.On("RemoveTunnel", conf)}
}

func (_c *TunnelManager_RemoveTunnel_Call) Run(run func(conf tunnel.TunnelConfig)) *TunnelManager_RemoveTunnel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tunnel.TunnelConfig
		if args[0] != nil {
			arg0 = args[0].(tunnel.TunnelConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TunnelManager_RemoveTunnel_Call) Return(err error) *TunnelManager_RemoveTunnel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TunnelManager_RemoveTunnel_Call) RunAndReturn(run func(conf tunnel.TunnelConfig) error) *TunnelManager_RemoveTunnel_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRemotePorts provides a mock function for the type TunnelManager
func (_mock *TunnelManager) SaveRemotePorts(payload common.TransitionPayload) error {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for SaveRemotePorts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(common.TransitionPayload) error); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TunnelManager_SaveRemotePorts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRemotePorts'
type TunnelManager_SaveRemotePorts_Call struct {
	*mock.Call
}

// SaveRemotePorts is a helper method to define mock.On call
//   - payload common.TransitionPayload
func (_e *TunnelManager_Expecter) SaveRemotePorts(payload any) *TunnelManager_SaveRemotePorts_Call {
	return &TunnelManager_SaveRemotePorts_Call{Call: _e.mock.On("SaveRemotePorts", payload)}
}

func (_c *TunnelManager_SaveRemotePorts_Call) Run(run func(payload common.TransitionPayload)) *TunnelManager_SaveRemotePorts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 common.TransitionPayload
		if args[0] != nil {
			arg0 = args[0].(common.TransitionPayload)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TunnelManager_SaveRemotePorts_Call) Return(err error) *TunnelManager_SaveRemotePorts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TunnelManager_SaveRemotePorts_Call) RunAndReturn(run func(payload common.TransitionPayload) error) *TunnelManager_SaveRemotePorts_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type TunnelManager
func (_mock *TunnelManager) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TunnelManager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type TunnelManager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *TunnelManager_Expecter) Start() *TunnelManager_Start_Call {
	return &TunnelManager_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *TunnelManager_Start_Call) Run(run func()) *TunnelManager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TunnelManager_Start_Call) Return(err error) *TunnelManager_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TunnelManager_Start_Call) RunAndReturn(run func() error) *TunnelManager_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type TunnelManager
func (_mock *TunnelManager) Status(tunnelID string) (tunnel.TunnelStatus, error) {
	ret := _mock.Called(tunnelID)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 tunnel.TunnelStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (tunnel.TunnelStatus, error)); ok {
		return returnFunc(tunnelID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) tunnel.TunnelStatus); ok {
		r0 = returnFunc(tunnelID)
	} else {
		r0 = ret.Get(0).(tunnel.TunnelStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tunnelID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TunnelManager_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type TunnelManager_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - tunnelID string
func (_e *TunnelManager_Expecter) Status(tunnelID any) *TunnelManager_Status_Call {
	return &TunnelManager_Status_Call{Call: _e.mock.On("Status", tunnelID)}
}

func (_c *TunnelManager_Status_Call) Run(run func(tunnelID string)) *TunnelManager_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TunnelManager_Status_Call) Return(tunnelStatus tunnel.TunnelStatus, err error) *TunnelManager_Status_Call {
	_c.Call.Return(tunnelStatus, err)
	return _c
}

func (_c *TunnelManager_Status_Call) RunAndReturn(run func(tunnelID string) (tunnel.TunnelStatus, error)) *TunnelManager_Status_Call {
	_c.Call.Return(run)
	return _c
}
