CREATE TABLE IF NOT EXISTS "DeviceStates" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  interfaceType TEXT CHECK( interfaceType IN ('WLAN', 'ETHERNET', 'NONE') ) NOT NULL,
  deviceStatus TEXT CHECK( deviceStatus IN ('CONNECTED', 'DISCONNECTED') ) NOT NULL,
  timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "DeviceStateHistory" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  interfaceType TEXT CHECK( interfaceType IN ('WLAN', 'ETHERNET', 'NONE') ) NOT NULL,
  deviceStatus TEXT CHECK( deviceStatus IN ('CONNECTED', 'DISCONNECTED') ) NOT NULL,
  timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "AppStates" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  appName TEXT NOT NULL,
  appKey INTEGER NOT NULL,
  stage TEXT CHECK( stage IN ('DEV', 'PROD') ) NOT NULL,
  state TEXT CHECK( state IN ('PRESENT', 'REMOVED', 'UNINSTALLED', 'FAILED', 'BUILDING', 'TRANSFERRED', 'TRANSFERRING', 'PUBLISHING', 'DOWNLOADING', 'STARTING', 'STOPPING', 'UPDATING', 'DELETING', 'RUNNING') ) NOT NULL,
  timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "AppStateHistory" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  appName TEXT NOT NULL,
  appKey INTEGER NOT NULL,
  stage TEXT CHECK( stage IN ('DEV', 'PROD') ) NOT NULL,
  state TEXT CHECK( state IN ('PRESENT', 'REMOVED', 'UNINSTALLED', 'FAILED', 'BUILDING', 'TRANSFERRED', 'TRANSFERRING', 'PUBLISHING', 'DOWNLOADING', 'STARTING', 'STOPPING', 'UPDATING', 'DELETING', 'RUNNING') ) NOT NULL,
  timestamp TEXT NOT NULL
);