// Code generated by "stringer -type=NmActiveConnectionStateReason"; DO NOT EDIT.

package networkmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NmActiveConnectionStateReasonUnknown-0]
	_ = x[NmActiveConnectionStateReasonNone-1]
	_ = x[NmActiveConnectionStateReasonUserDisconnected-2]
	_ = x[NmActiveConnectionStateReasonDeviceDisconnected-3]
	_ = x[NmActiveConnectionStateReasonServiceStopped-4]
	_ = x[NmActiveConnectionStateReasonIpConfigInvalid-5]
	_ = x[NmActiveConnectionStateReasonConnectTimeout-6]
	_ = x[NmActiveConnectionStateReasonServiceStartTimeout-7]
	_ = x[NmActiveConnectionStateReasonServiceStartFailed-8]
	_ = x[NmActiveConnectionStateReasonNoSecrets-9]
	_ = x[NmActiveConnectionStateReasonLoginFailed-10]
	_ = x[NmActiveConnectionStateReasonConnectionRemoved-11]
	_ = x[NmActiveConnectionStateReasonDependencyFailed-12]
	_ = x[NmActiveConnectionStateReasonDeviceRealizeFailed-13]
	_ = x[NmActiveConnectionStateReasonDeviceRemoved-14]
}

const _NmActiveConnectionStateReason_name = "NmActiveConnectionStateReasonUnknownNmActiveConnectionStateReasonNoneNmActiveConnectionStateReasonUserDisconnectedNmActiveConnectionStateReasonDeviceDisconnectedNmActiveConnectionStateReasonServiceStoppedNmActiveConnectionStateReasonIpConfigInvalidNmActiveConnectionStateReasonConnectTimeoutNmActiveConnectionStateReasonServiceStartTimeoutNmActiveConnectionStateReasonServiceStartFailedNmActiveConnectionStateReasonNoSecretsNmActiveConnectionStateReasonLoginFailedNmActiveConnectionStateReasonConnectionRemovedNmActiveConnectionStateReasonDependencyFailedNmActiveConnectionStateReasonDeviceRealizeFailedNmActiveConnectionStateReasonDeviceRemoved"

var _NmActiveConnectionStateReason_index = [...]uint16{0, 36, 69, 114, 161, 204, 248, 291, 339, 386, 424, 464, 510, 555, 603, 645}

func (i NmActiveConnectionStateReason) String() string {
	if i >= NmActiveConnectionStateReason(len(_NmActiveConnectionStateReason_index)-1) {
		return "NmActiveConnectionStateReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NmActiveConnectionStateReason_name[_NmActiveConnectionStateReason_index[i]:_NmActiveConnectionStateReason_index[i+1]]
}
