# This Makefile is created for the testers convenience.

install:
	echo "get the install_reagent from a link"
	sudo chmod 777 install_reagent.sh
	./install_reagent.sh

upload:
	gsutil cp ./install_reagent.sh gs://re-agent/install/install_reagent.sh