# This Makefile is created for the testers convenience. 

install_reagent:
	echo "get the install_reagent from a link"
	sudo chmod 777 install_reagent.sh
	./install_reagent.sh darwin 10.6 amd64

uninstall_reagent:
	echo "uninstall all reagent folders according to OS, i.e. binary folder" 
