#!/bin/sh

# Reagent initialization in /etc/init.d/S97reagent

# check for *.reswarm file in /boot directory
reswmexst=$(ls /boot/ | grep -E ".reswarm" | head -n1)

if [ -z ${reswmexst} ]; then
  echo "no reswarm configuration file found => not going to run the agent"
  exit 1
else
  echo "found reswarm file: ${reswmexst} => going to launch agent..."
fi

# evtl. use CLI parameters given reswarm file
# TODO
appsDir=""
cbldExt=""
resfile=""
debug=""
logfile=""

# use constant executable name (TODO: include version number and architecture)
REAGENT="/opt/reagent/reagent-v0.1"

case "$1" in

  start)

    $(REAGENT) -appsDirectory $(appsDir) -compressedBuildExtension $(cbldExt) -config $(resfile) -logfile $(logfile)
    ;;

  stop)

    ;;

  restart)

    ;;

  *)

    echo "Usage: $0 start"
    exit 1
    ;;

esac
